/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Principal;

import Interface.CustomizarTabela.CustomCabecalhoJTable;
import Interface.CustomizarTabela.CustomCelulaJTable;
import Negocio.Diversos;
import Persistencia.DaoConsulta;
import java.awt.Color;
import java.util.Timer;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Pedro
 */
public class JFrmPedidosByTime extends javax.swing.JFrame
{

    /**
     * Creates new form JFrmPedidosByTime
     */
    public JFrmPedidosByTime()
    {
        initComponents();
        sincronizarBanco();
        customizeTable();
        setLimite();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLblVoltar = new javax.swing.JLabel();
        jLblTitulo = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblPedidos = new javax.swing.JTable();
        Logo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pedidos by Time");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jLblVoltar.setBackground(new java.awt.Color(204, 0, 0));
        jLblVoltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jLblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVoltar.setText("←");
        jLblVoltar.setToolTipText("Voltar");
        jLblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblVoltarMouseClicked(evt);
            }
        });

        jLblTitulo.setFont(new java.awt.Font("Segoe UI Light", 3, 36)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblTitulo.setText("Pedidos em Andamento");

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.getViewport().setBackground(new Color(0,0,0));

        jTblPedidos.setBackground(new java.awt.Color(0, 0, 0));
        jTblPedidos.setGridColor(new java.awt.Color(255, 255, 255));
        jTblPedidos.setRowHeight(25);
        jScrollPane1.setViewportView(jTblPedidos);

        Logo.setBackground(new java.awt.Color(51, 51, 51));
        Logo.setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/c5.png"))); // NOI18N
        Logo.add(jLabel3);
        jLabel3.setBounds(0, 0, 69, 66);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("A");
        Logo.add(jLabel2);
        jLabel2.setBounds(22, 5, 25, 48);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 711, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Persistencia
        static DaoConsulta dC = new DaoConsulta();
    //Negocio
    
    //Interface
        static DefaultTableModel dtm;
        static CustomCelulaJTable tdRenderer = new CustomCelulaJTable(2);
    //Variaveis de Controle
        static String dataIni[];
        static int secs = 0; //Segundos passados
        static int limit = 20;//atualizar dados de 20 em 20 secs
        static boolean go = true;
    
    public static void sincronizarBanco()//Reefazer a consulta no banco
    {
        dtm = dC.retornaLista(14, "");
        jTblPedidos.setModel(dtm);
        dataIni = new String[dtm.getRowCount()];
        for (int i = 0; i < dataIni.length; i++)
        {
            dataIni[i] = (String) dtm.getValueAt(i, 5);
        }
    }
    public static Thread attTable()//Atualiza a tabela de 1 em 1 segundo
    {
        Thread t = new Thread()
        {
            public void run()
            {
                go = true;
                while (go)
                {
                    try
                    {
                        if (secs == limit)//Se ja se passou o tempo limite refaz a consulta
                        {
                            sincronizarBanco();
                            customizeTable();
                            secs = 0;
                        }
                        Thread.sleep(1000);
                        for (int i = 0; i < dataIni.length; i++)
                        {
                            dtm.setValueAt(Diversos.tempoDecorrido(dataIni[i]), i, 5);
                        }
                        secs++;
                    } catch (Exception ex)
                    {
                        //ex.printStackTrace();
                    }
                }
            }
        };
        return t;
    }
    public static void customizeTable()//Pinta a tabela
    {
        for (int i = 0; i < 6; i++)
        {
            jTblPedidos.getColumnModel().getColumn(i).setCellRenderer(tdRenderer);
            jTblPedidos.getColumnModel().getColumn(i).setHeaderRenderer(new CustomCabecalhoJTable(2));
        }
        jTblPedidos.setCellSelectionEnabled(true);
        jTblPedidos.setSelectionBackground(Color.BLUE);
    }
    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblVoltarMouseClicked
    {//GEN-HEADEREND:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        go = false;
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked
    /*public static void start()
    Só funciona quando é executada diretamente pelo metodo principal
    quando ela é chamada por outra tela, entra no loop e não sai, o que é mal
    pq nem da tempo de carregar os negocio na tela
    {
        while(true)
        {
            try
            {
                if(secs == limit)
                {
                    sincronizarBanco();
                    customizeTable();
                    secs = 0;
                }
                Thread.sleep(1000);
                for(int i = 0; i < dataIni.length; i++)
                {
                    dtm.setValueAt(Diversos.tempoDecorrido(dataIni[i]), i, 5);
                }
                secs++;
            } catch (InterruptedException ex)
            {
                Logger.getLogger(JFrmPedidosByTime.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }*/
    public static void setLimite()
    {
        String lim = Diversos.leDados("Selecione o tempo de sincronismo com"
                                            + " o servidor:\n.15 Segundos\n.20 Segundos (Recomendado)"
                                            + "\n.40 Segundos\n.60 Segundos", "Tempo de sincronismo");
        if(Diversos.testaNum(lim, "Exception"))
        {
            limit = Integer.parseInt(lim);
        }
        else
        {
            Diversos.mostrarDados("Tempo de sincroniza setado para 20s", "22:04", true);
            limit = 20;
        }
        attTable().start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPedidosByTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPedidosByTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPedidosByTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPedidosByTime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        new JFrmPedidosByTime().setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private static javax.swing.JTable jTblPedidos;
    // End of variables declaration//GEN-END:variables

    
}
