/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Principal;

import Interface.AtendenteView.JFrmPedido;
import Interface.EntregadorView.JFrmEntregadorPedido;
import Interface.GerenteView.JFrmEntregador;
import Interface.GerenteView.JFrmIngrediente;
import Interface.GerenteView.JFrmLote;
import Interface.GerenteView.JFrmPrato;
import Negocio.Diversos;
import Persistencia.DaoConexao;
import Relatorios.ReportUtils;
import java.awt.Color;
import java.awt.Component;
import java.io.InputStream;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.Map;
import javax.swing.BorderFactory;
import net.sf.jasperreports.engine.JRException;

/**
 *
 * @author Pedro
 */
public class JFrmPrincipal extends javax.swing.JFrame
{

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal()
    {
        initComponents();
        showAtt(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton15 = new javax.swing.JButton();
        jPnlConsulta = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLblSair = new javax.swing.JLabel();
        jPnlNotificacoes = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTxtAreaMenssagem = new javax.swing.JTextArea();
        jBtnAttYellow = new javax.swing.JButton();
        jBtnAttRed = new javax.swing.JButton();
        jLblConfig = new javax.swing.JLabel();
        jPnlControle = new javax.swing.JPanel();
        jBtnEntregadores = new javax.swing.JButton();
        jBtnIngredientes = new javax.swing.JButton();
        jBtnLotes = new javax.swing.JButton();
        jBtnPratos = new javax.swing.JButton();
        jLblControle = new javax.swing.JLabel();
        jBtnConfirmacaoPedido1 = new javax.swing.JButton();
        jPnlNegocio = new javax.swing.JPanel();
        jBtnPedido = new javax.swing.JButton();
        jBtnPedidosEmAndamento = new javax.swing.JButton();
        jBtnConfirmacaoPedido = new javax.swing.JButton();
        jLblNegocio = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jBtnTotalEstoque = new javax.swing.JButton();
        jBtnListaPrato = new javax.swing.JButton();
        jBtnUsoIngrediente = new javax.swing.JButton();
        jBtnListaPedido = new javax.swing.JButton();
        jBtnVendas = new javax.swing.JButton();
        jBtnForaValidade = new javax.swing.JButton();
        jBtnAbaixoEstoque = new javax.swing.JButton();
        jLblConsultas = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 255), 2));
        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        jPanel3.setBackground(new java.awt.Color(22, 73, 154));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/attreal.png"))); // NOI18N
        jLabel9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/attyellowrealjj.png"))); // NOI18N
        jLabel10.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 102, 102), 4));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTextArea3.setEditable(false);
        jTextArea3.setBackground(new java.awt.Color(255, 102, 102));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(0, 0, 0));
        jTextArea3.setLineWrap(true);
        jTextArea3.setRows(5);
        jTextArea3.setText("Devido a ultima Time War por enquanto não é possível editar a lista de ingredientes usada em um prato.");
        jScrollPane3.setViewportView(jTextArea3);

        jButton15.setBackground(new java.awt.Color(22, 73, 154));
        jButton15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/attyellowrealjj.png"))); // NOI18N
        jButton15.setBorderPainted(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 24, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("August");
        setUndecorated(true);

        jPnlConsulta.setBackground(new java.awt.Color(22, 73, 154));
        jPnlConsulta.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jPnlConsulta.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jPnlConsultaMouseClicked(evt);
            }
        });
        jPnlConsulta.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusGained(java.awt.event.FocusEvent evt)
            {
                jPnlConsultaFocusGained(evt);
            }
        });

        Logo.setBackground(new java.awt.Color(22, 73, 154));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/c5.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("August");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3)
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jLblSair.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLblSair.setForeground(new java.awt.Color(255, 51, 51));
        jLblSair.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblSair.setText("X");
        jLblSair.setToolTipText("Sair");
        jLblSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0)));
        jLblSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblSair.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblSairMouseClicked(evt);
            }
        });

        jPnlNotificacoes.setBackground(new java.awt.Color(22, 73, 154));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(193, 36, 45), 2));
        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane4.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        jTxtAreaMenssagem.setEditable(false);
        jTxtAreaMenssagem.setBackground(new java.awt.Color(255, 102, 102));
        jTxtAreaMenssagem.setColumns(20);
        jTxtAreaMenssagem.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jTxtAreaMenssagem.setForeground(new java.awt.Color(0, 0, 0));
        jTxtAreaMenssagem.setLineWrap(true);
        jTxtAreaMenssagem.setRows(5);
        jTxtAreaMenssagem.setName("CaixaTexto"); // NOI18N
        jScrollPane4.setViewportView(jTxtAreaMenssagem);

        jBtnAttYellow.setBackground(new java.awt.Color(22, 73, 154));
        jBtnAttYellow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/attyellowrealjj.png"))); // NOI18N
        jBtnAttYellow.setBorderPainted(false);
        jBtnAttYellow.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAttYellow.setFocusPainted(false);
        jBtnAttYellow.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAttYellowActionPerformed(evt);
            }
        });
        jBtnAttYellow.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jBtnAttYellowFocusLost(evt);
            }
        });

        jBtnAttRed.setBackground(new java.awt.Color(22, 73, 154));
        jBtnAttRed.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/attreal.png"))); // NOI18N
        jBtnAttRed.setBorderPainted(false);
        jBtnAttRed.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAttRed.setFocusPainted(false);
        jBtnAttRed.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAttRedActionPerformed(evt);
            }
        });
        jBtnAttRed.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jBtnAttRedFocusLost(evt);
            }
        });

        jLblConfig.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblConfig.setForeground(new java.awt.Color(255, 255, 255));
        jLblConfig.setText("Config");
        jLblConfig.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblConfig.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblConfigMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlNotificacoesLayout = new javax.swing.GroupLayout(jPnlNotificacoes);
        jPnlNotificacoes.setLayout(jPnlNotificacoesLayout);
        jPnlNotificacoesLayout.setHorizontalGroup(
            jPnlNotificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlNotificacoesLayout.createSequentialGroup()
                .addGroup(jPnlNotificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPnlNotificacoesLayout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlNotificacoesLayout.createSequentialGroup()
                        .addComponent(jBtnAttRed, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAttYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLblConfig, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlNotificacoesLayout.setVerticalGroup(
            jPnlNotificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlNotificacoesLayout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addGroup(jPnlNotificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlNotificacoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jBtnAttYellow, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnAttRed, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLblConfig, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPnlControle.setBackground(new java.awt.Color(22, 73, 154));

        jBtnEntregadores.setBackground(new java.awt.Color(102, 102, 255));
        jBtnEntregadores.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnEntregadores.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEntregadores.setText("Entregadores");
        jBtnEntregadores.setBorderPainted(false);
        jBtnEntregadores.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnEntregadores.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnEntregadoresActionPerformed(evt);
            }
        });

        jBtnIngredientes.setBackground(new java.awt.Color(102, 102, 255));
        jBtnIngredientes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnIngredientes.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIngredientes.setText("Ingredientes");
        jBtnIngredientes.setBorderPainted(false);
        jBtnIngredientes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnIngredientes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnIngredientesActionPerformed(evt);
            }
        });

        jBtnLotes.setBackground(new java.awt.Color(102, 102, 255));
        jBtnLotes.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnLotes.setForeground(new java.awt.Color(255, 255, 255));
        jBtnLotes.setText("Lotes");
        jBtnLotes.setBorderPainted(false);
        jBtnLotes.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnLotes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnLotesActionPerformed(evt);
            }
        });

        jBtnPratos.setBackground(new java.awt.Color(102, 102, 255));
        jBtnPratos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPratos.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPratos.setText("Pratos");
        jBtnPratos.setBorderPainted(false);
        jBtnPratos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPratos.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnPratosActionPerformed(evt);
            }
        });

        jLblControle.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLblControle.setForeground(new java.awt.Color(255, 255, 255));
        jLblControle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblControle.setText("Controle");

        jBtnConfirmacaoPedido1.setBackground(new java.awt.Color(102, 102, 255));
        jBtnConfirmacaoPedido1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnConfirmacaoPedido1.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConfirmacaoPedido1.setText("Gerar Folha de Pagamento");
        jBtnConfirmacaoPedido1.setBorderPainted(false);
        jBtnConfirmacaoPedido1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnConfirmacaoPedido1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnConfirmacaoPedido1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPnlControleLayout = new javax.swing.GroupLayout(jPnlControle);
        jPnlControle.setLayout(jPnlControleLayout);
        jPnlControleLayout.setHorizontalGroup(
            jPnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBtnEntregadores, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
            .addComponent(jBtnIngredientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnLotes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnPratos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLblControle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnConfirmacaoPedido1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnlControleLayout.setVerticalGroup(
            jPnlControleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlControleLayout.createSequentialGroup()
                .addComponent(jLblControle, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnEntregadores, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnIngredientes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnLotes, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPratos, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnConfirmacaoPedido1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 117, Short.MAX_VALUE))
        );

        jPnlNegocio.setBackground(new java.awt.Color(22, 73, 154));

        jBtnPedido.setBackground(new java.awt.Color(102, 102, 255));
        jBtnPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPedido.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPedido.setText("Pedido");
        jBtnPedido.setBorderPainted(false);
        jBtnPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPedido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnPedidoActionPerformed(evt);
            }
        });

        jBtnPedidosEmAndamento.setBackground(new java.awt.Color(102, 102, 255));
        jBtnPedidosEmAndamento.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnPedidosEmAndamento.setForeground(new java.awt.Color(255, 255, 255));
        jBtnPedidosEmAndamento.setText("Pedidos em Andamento");
        jBtnPedidosEmAndamento.setBorderPainted(false);
        jBtnPedidosEmAndamento.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnPedidosEmAndamento.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnPedidosEmAndamentoActionPerformed(evt);
            }
        });

        jBtnConfirmacaoPedido.setBackground(new java.awt.Color(102, 102, 255));
        jBtnConfirmacaoPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnConfirmacaoPedido.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConfirmacaoPedido.setText("Confirmação Pedido");
        jBtnConfirmacaoPedido.setBorderPainted(false);
        jBtnConfirmacaoPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnConfirmacaoPedido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnConfirmacaoPedidoActionPerformed(evt);
            }
        });

        jLblNegocio.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLblNegocio.setForeground(new java.awt.Color(255, 255, 255));
        jLblNegocio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNegocio.setText("Negocio");

        javax.swing.GroupLayout jPnlNegocioLayout = new javax.swing.GroupLayout(jPnlNegocio);
        jPnlNegocio.setLayout(jPnlNegocioLayout);
        jPnlNegocioLayout.setHorizontalGroup(
            jPnlNegocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblNegocio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnPedidosEmAndamento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
            .addComponent(jBtnConfirmacaoPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPnlNegocioLayout.setVerticalGroup(
            jPnlNegocioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlNegocioLayout.createSequentialGroup()
                .addComponent(jLblNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnPedidosEmAndamento, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnConfirmacaoPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(229, Short.MAX_VALUE))
        );

        jPanel7.setBackground(new java.awt.Color(22, 73, 154));

        jBtnTotalEstoque.setBackground(new java.awt.Color(102, 102, 255));
        jBtnTotalEstoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnTotalEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jBtnTotalEstoque.setText("Total Estoque(R$)");
        jBtnTotalEstoque.setBorderPainted(false);
        jBtnTotalEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnTotalEstoque.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnTotalEstoqueActionPerformed(evt);
            }
        });

        jBtnListaPrato.setBackground(new java.awt.Color(102, 102, 255));
        jBtnListaPrato.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnListaPrato.setForeground(new java.awt.Color(255, 255, 255));
        jBtnListaPrato.setText("Listar Pratos");
        jBtnListaPrato.setBorderPainted(false);
        jBtnListaPrato.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnListaPrato.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnListaPratoActionPerformed(evt);
            }
        });

        jBtnUsoIngrediente.setBackground(new java.awt.Color(102, 102, 255));
        jBtnUsoIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnUsoIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        jBtnUsoIngrediente.setText("Uso de Ingrediente");
        jBtnUsoIngrediente.setBorderPainted(false);
        jBtnUsoIngrediente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnUsoIngrediente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnUsoIngredienteActionPerformed(evt);
            }
        });

        jBtnListaPedido.setBackground(new java.awt.Color(102, 102, 255));
        jBtnListaPedido.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnListaPedido.setForeground(new java.awt.Color(255, 255, 255));
        jBtnListaPedido.setText("Listar Pedidos");
        jBtnListaPedido.setBorderPainted(false);
        jBtnListaPedido.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnListaPedido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnListaPedidoActionPerformed(evt);
            }
        });

        jBtnVendas.setBackground(new java.awt.Color(102, 102, 255));
        jBtnVendas.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnVendas.setForeground(new java.awt.Color(255, 255, 255));
        jBtnVendas.setText("Vendas");
        jBtnVendas.setBorderPainted(false);
        jBtnVendas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnVendas.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnVendasActionPerformed(evt);
            }
        });

        jBtnForaValidade.setBackground(new java.awt.Color(102, 102, 255));
        jBtnForaValidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnForaValidade.setForeground(new java.awt.Color(255, 255, 255));
        jBtnForaValidade.setText("Fora Validade");
        jBtnForaValidade.setBorderPainted(false);
        jBtnForaValidade.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnForaValidade.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnForaValidadeActionPerformed(evt);
            }
        });

        jBtnAbaixoEstoque.setBackground(new java.awt.Color(102, 102, 255));
        jBtnAbaixoEstoque.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnAbaixoEstoque.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAbaixoEstoque.setText("Abaixo Estoque Min");
        jBtnAbaixoEstoque.setBorderPainted(false);
        jBtnAbaixoEstoque.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAbaixoEstoque.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAbaixoEstoqueActionPerformed(evt);
            }
        });

        jLblConsultas.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLblConsultas.setForeground(new java.awt.Color(255, 255, 255));
        jLblConsultas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblConsultas.setText("Consultas");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnForaValidade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnUsoIngrediente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnTotalEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnListaPedido, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnListaPrato, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jBtnAbaixoEstoque, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jLblConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnForaValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnUsoIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnTotalEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnListaPedido, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnListaPrato, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jBtnAbaixoEstoque, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPnlConsultaLayout = new javax.swing.GroupLayout(jPnlConsulta);
        jPnlConsulta.setLayout(jPnlConsultaLayout);
        jPnlConsultaLayout.setHorizontalGroup(
            jPnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlConsultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPnlNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPnlConsultaLayout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlConsultaLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                        .addComponent(jPnlNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jPnlControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPnlConsultaLayout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPnlConsultaLayout.setVerticalGroup(
            jPnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlConsultaLayout.createSequentialGroup()
                .addGroup(jPnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPnlConsultaLayout.createSequentialGroup()
                        .addComponent(jPnlNotificacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1)
                            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPnlConsultaLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(jPnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPnlConsultaLayout.createSequentialGroup()
                                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPnlNegocio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPnlConsultaLayout.createSequentialGroup()
                                .addComponent(jLblSair, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPnlConsultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPnlConsultaLayout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addComponent(jSeparator2))
                                    .addGroup(jPnlConsultaLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPnlControle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(38, 38, 38))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPnlConsulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    public void showAtt(int op)//Comportamento das notificações...
    {
        Color bgColor;
        Color textColor;
        Color baseBgColor;
        boolean see;
        String text;
        if(op == 1)
        {
            bgColor = new Color(22,73,154);
            textColor = bgColor;
            baseBgColor = bgColor;
            see = false;
            text = "";
        }
        else if(op == 2)
        {
            bgColor = new Color(255, 102, 102);
            textColor = Color.BLACK;
            baseBgColor = new Color(193,36,45);
            see = true;
            text = "Devido a ultima Time War por enquanto não é possível editar a"
                 + " lista de ingredientes usada em um prato.";
        }
        else
        {
            bgColor = new Color(255,150,20);
            textColor = Color.BLACK;
            baseBgColor = Color.YELLOW;
            see = true;
            text = "Foi descoberto um bug em 'Pedidos em Andamento' que gera uma Exception"
                 + " inesperada no console.";
        }
        jTxtAreaMenssagem.setText(text);
        jTxtAreaMenssagem.setForeground(textColor);
        jTxtAreaMenssagem.setBackground(bgColor);
        jScrollPane4.setBorder(javax.swing.BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(baseBgColor, 1),
                BorderFactory.createLineBorder(bgColor, 3)));
    }
    private void jBtnAbaixoEstoqueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAbaixoEstoqueActionPerformed
    {//GEN-HEADEREND:event_jBtnAbaixoEstoqueActionPerformed
        // TODO add your handling code here:
        new JFrmConsulta(7, "Ingredientes Abaixo do Estoque", "").setVisible(true);
    }//GEN-LAST:event_jBtnAbaixoEstoqueActionPerformed

    private void jBtnForaValidadeActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnForaValidadeActionPerformed
    {//GEN-HEADEREND:event_jBtnForaValidadeActionPerformed
        // TODO add your handling code here:
        new JFrmConsulta(6, "Lotes Fora Vallidade", "").setVisible(true);
    }//GEN-LAST:event_jBtnForaValidadeActionPerformed

    private void jLblConfigMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblConfigMouseClicked
    {//GEN-HEADEREND:event_jLblConfigMouseClicked
        // TODO add your handling code here:
        Diversos.mostrarDados(
                "Para melhor vizualização do conteúdo tenha instalado em\n"
              + "seu computador as seguintes fontes: 'Segoe UI' e 'Segoe UI Light'.\n"
              + "Essas fontes podem ser encontradas na pasta deste aplicativo.", "Fonte", true);
        if(Diversos.confirmar("Deseja habilitar colocação de imgs no cadastro de Entregadores?", "IMG"))
        {
            Diversos.setNomeOs();
        }
        else
        {
            Diversos.HABILITAR = false;
        }
        Diversos.mostrarDados("Desenvolvido por: Pedro Augusto\n", "Wibbly Wobbly Timey Wimey", true);
    }//GEN-LAST:event_jLblConfigMouseClicked

    private void jLblSairMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblSairMouseClicked
    {//GEN-HEADEREND:event_jLblSairMouseClicked
        // TODO add your handling code here:
        if(Diversos.confirmar("Deseja realmente sair?", "Sair"))
        System.exit(0);
    }//GEN-LAST:event_jLblSairMouseClicked

    private void jBtnPratosActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnPratosActionPerformed
    {//GEN-HEADEREND:event_jBtnPratosActionPerformed
        // TODO add your handling code here:
        new JFrmPrato().setVisible(true);
    }//GEN-LAST:event_jBtnPratosActionPerformed

    private void jBtnLotesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnLotesActionPerformed
    {//GEN-HEADEREND:event_jBtnLotesActionPerformed
        // TODO add your handling code here:
        new JFrmLote(null, null).setVisible(true);
    }//GEN-LAST:event_jBtnLotesActionPerformed

    private void jBtnIngredientesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnIngredientesActionPerformed
    {//GEN-HEADEREND:event_jBtnIngredientesActionPerformed
        // TODO add your handling code here:
        new JFrmIngrediente().setVisible(true);
    }//GEN-LAST:event_jBtnIngredientesActionPerformed

    private void jBtnEntregadoresActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnEntregadoresActionPerformed
    {//GEN-HEADEREND:event_jBtnEntregadoresActionPerformed
        // TODO add your handling code here:
        new JFrmEntregador().setVisible(true);
    }//GEN-LAST:event_jBtnEntregadoresActionPerformed

    private void jBtnPedidosEmAndamentoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnPedidosEmAndamentoActionPerformed
    {//GEN-HEADEREND:event_jBtnPedidosEmAndamentoActionPerformed
        // TODO add your handling code here:
        JFrmPedidosByTime listaTempo = new JFrmPedidosByTime();
        listaTempo.setVisible(true);
    }//GEN-LAST:event_jBtnPedidosEmAndamentoActionPerformed

    private void jBtnConfirmacaoPedidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnConfirmacaoPedidoActionPerformed
    {//GEN-HEADEREND:event_jBtnConfirmacaoPedidoActionPerformed
        // TODO add your handling code here:
        new JFrmEntregadorPedido().setVisible(true);
    }//GEN-LAST:event_jBtnConfirmacaoPedidoActionPerformed

    private void jBtnPedidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnPedidoActionPerformed
    {//GEN-HEADEREND:event_jBtnPedidoActionPerformed
        // TODO add your handling code here:
        new JFrmPedido().setVisible(true);
    }//GEN-LAST:event_jBtnPedidoActionPerformed

    private void jBtnVendasActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnVendasActionPerformed
    {//GEN-HEADEREND:event_jBtnVendasActionPerformed
        // TODO add your handling code here:
        new JFrmConsulta(5, "Lista de Vendas", "").setVisible(true);
    }//GEN-LAST:event_jBtnVendasActionPerformed

    private void jBtnListaPedidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnListaPedidoActionPerformed
    {//GEN-HEADEREND:event_jBtnListaPedidoActionPerformed
        // TODO add your handling code here:
        new JFrmConsulta(4, "Lista de Pedidos", "").setVisible(true);
    }//GEN-LAST:event_jBtnListaPedidoActionPerformed

    private void jBtnUsoIngredienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnUsoIngredienteActionPerformed
    {//GEN-HEADEREND:event_jBtnUsoIngredienteActionPerformed
        // TODO add your handling code here:
        new JFrmConsulta(3, "Ingredientes e seus Pratos", "").setVisible(true);
    }//GEN-LAST:event_jBtnUsoIngredienteActionPerformed

    private void jBtnListaPratoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnListaPratoActionPerformed
    {//GEN-HEADEREND:event_jBtnListaPratoActionPerformed
        // TODO add your handling code here:
        new JFrmConsulta(2, "Lista de Pratos", "").setVisible(true);
    }//GEN-LAST:event_jBtnListaPratoActionPerformed

    private void jBtnTotalEstoqueActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnTotalEstoqueActionPerformed
    {//GEN-HEADEREND:event_jBtnTotalEstoqueActionPerformed
        // TODO add your handling code here:
        new JFrmConsulta(1, "Valor em Estoque(R$)", "").setVisible(true);
    }//GEN-LAST:event_jBtnTotalEstoqueActionPerformed

    private void jBtnAttRedActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAttRedActionPerformed
    {//GEN-HEADEREND:event_jBtnAttRedActionPerformed
        // TODO add your handling code here:
        showAtt(2);
    }//GEN-LAST:event_jBtnAttRedActionPerformed

    private void jBtnAttRedFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jBtnAttRedFocusLost
    {//GEN-HEADEREND:event_jBtnAttRedFocusLost
        // TODO add your handling code here:
        String novoComp = null;
        try
        {
            novoComp = evt.getOppositeComponent().getName();
        } catch (Exception e)
        {
            //Caso eu ponha o que o if abaixo faz aqui dentro continua dando erro
        }
        if(novoComp == null)
           novoComp = "Timey Wimey";
        if(!novoComp.equals("CaixaTexto"))
            showAtt(1);
    }//GEN-LAST:event_jBtnAttRedFocusLost

    private void jBtnAttYellowActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAttYellowActionPerformed
    {//GEN-HEADEREND:event_jBtnAttYellowActionPerformed
        // TODO add your handling code here:
        showAtt(3);
    }//GEN-LAST:event_jBtnAttYellowActionPerformed

    private void jBtnAttYellowFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jBtnAttYellowFocusLost
    {//GEN-HEADEREND:event_jBtnAttYellowFocusLost
        // TODO add your handling code here:
        String novoComp = null;
        try
        {
            novoComp = evt.getOppositeComponent().getName();
        } catch (Exception e)
        {
            //Caso eu ponha o que o if abaixo faz aqui dentro continua dando erro
        }
        if(novoComp == null)
            novoComp = "Timey Wimey";
        if(!novoComp.equals("CaixaTexto"))
        showAtt(1);
    }//GEN-LAST:event_jBtnAttYellowFocusLost

    private void jPnlConsultaFocusGained(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jPnlConsultaFocusGained
    {//GEN-HEADEREND:event_jPnlConsultaFocusGained
        // TODO add your handling code here:
        showAtt(1);
    }//GEN-LAST:event_jPnlConsultaFocusGained

    private void jPnlConsultaMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jPnlConsultaMouseClicked
    {//GEN-HEADEREND:event_jPnlConsultaMouseClicked
        // TODO add your handling code here:
        showAtt(1);
    }//GEN-LAST:event_jPnlConsultaMouseClicked

    private void jBtnConfirmacaoPedido1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnConfirmacaoPedido1ActionPerformed
    {//GEN-HEADEREND:event_jBtnConfirmacaoPedido1ActionPerformed
        // TODO add your handling code here:
        InputStream inputStream = getClass().getResourceAsStream("/relatórios/FolhaPagamento.jasper" );
        //System.out.println(getClass().getResource("/relatórios/FolhaPagamento.jrxml").getFile());
        // mapa de parâmetros do relatório (ainda vamos aprender a usar)
        Map parametros = new HashMap();
 
        try {
 
            // abre o relatório
            ReportUtils.openReport( "Clientes", inputStream, parametros,
                    DaoConexao.getConnection());
 
        } catch (Exception exc ) {
            exc.printStackTrace();
        }
    }//GEN-LAST:event_jBtnConfirmacaoPedido1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JButton jBtnAbaixoEstoque;
    private javax.swing.JButton jBtnAttRed;
    private javax.swing.JButton jBtnAttYellow;
    private javax.swing.JButton jBtnConfirmacaoPedido;
    private javax.swing.JButton jBtnConfirmacaoPedido1;
    private javax.swing.JButton jBtnEntregadores;
    private javax.swing.JButton jBtnForaValidade;
    private javax.swing.JButton jBtnIngredientes;
    private javax.swing.JButton jBtnListaPedido;
    private javax.swing.JButton jBtnListaPrato;
    private javax.swing.JButton jBtnLotes;
    private javax.swing.JButton jBtnPedido;
    private javax.swing.JButton jBtnPedidosEmAndamento;
    private javax.swing.JButton jBtnPratos;
    private javax.swing.JButton jBtnTotalEstoque;
    private javax.swing.JButton jBtnUsoIngrediente;
    private javax.swing.JButton jBtnVendas;
    private javax.swing.JButton jButton15;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLblConfig;
    private javax.swing.JLabel jLblConsultas;
    private javax.swing.JLabel jLblControle;
    private javax.swing.JLabel jLblNegocio;
    private javax.swing.JLabel jLblSair;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPnlConsulta;
    private javax.swing.JPanel jPnlControle;
    private javax.swing.JPanel jPnlNegocio;
    private javax.swing.JPanel jPnlNotificacoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTxtAreaMenssagem;
    // End of variables declaration//GEN-END:variables
}
