/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.Principal;
import Interface.CustomizarTabela.CustomCabecalhoJTable;
import Interface.CustomizarTabela.CustomCelulaJTable;
import Negocio.Diversos;
import Negocio.Entregador;
import Negocio.Ingrediente;
import Persistencia.DaoConsulta;
import Persistencia.DaoEntregador;
import Persistencia.DaoIngrediente;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Pedro
 */
public class JFrmConsulta extends javax.swing.JFrame
{

    /**
     * Creates new form JFrmConsulta
     */
    public JFrmConsulta(int op, String titulo, String par)
    {
        initComponents();
        selecionarTipo(op);
        jLblTitulo.setText(titulo);
        jTblConsulta.setModel(dC.retornaLista(op, par));
        lookAndFeel();
        customizeTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLblVoltar = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTblConsulta = new javax.swing.JTable();
        jLblTitulo = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jCmbMes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jCmbEntregador = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jCmbSessao = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jCmbIngrediente = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Consulta");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(22, 73, 154));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        jLblVoltar.setBackground(new java.awt.Color(204, 0, 0));
        jLblVoltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jLblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVoltar.setText("←");
        jLblVoltar.setToolTipText("Voltar");
        jLblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblVoltarMouseClicked(evt);
            }
        });

        jScrollPane1.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));
        jScrollPane1.getViewport().setBackground(new Color(102,102,255));

        jTblConsulta.setBackground(new java.awt.Color(102, 102, 255));
        jTblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {

            }
        ));
        jTblConsulta.setGridColor(new java.awt.Color(234, 234, 234));
        jTblConsulta.setRowHeight(25);
        jTblConsulta.setSelectionBackground(new java.awt.Color(0, 51, 153));
        jTblConsulta.setShowHorizontalLines(false);
        jTblConsulta.setShowVerticalLines(false);
        jScrollPane1.setViewportView(jTblConsulta);

        jLblTitulo.setFont(new java.awt.Font("Segoe UI Light", 3, 18)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Mês:");

        jCmbMes.setBackground(new java.awt.Color(102, 102, 255));
        jCmbMes.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCmbMes.setForeground(new java.awt.Color(255, 255, 255));
        jCmbMes.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Janeiro", "Fevereiro", "Março", "Abril", "Maio", "Junho", "Julho", "Agosto", "Setembro", "Outubro", "Novembro", "Dezembro" }));
        jCmbMes.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbMesActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Entregador:");

        jCmbEntregador.setBackground(new java.awt.Color(102, 102, 255));
        jCmbEntregador.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCmbEntregador.setForeground(new java.awt.Color(255, 255, 255));
        jCmbEntregador.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbEntregadorActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Sessão:");

        jCmbSessao.setBackground(new java.awt.Color(102, 102, 255));
        jCmbSessao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCmbSessao.setForeground(new java.awt.Color(255, 255, 255));
        jCmbSessao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Sobremesa", "Entrada", "Massa", "Carne" }));
        jCmbSessao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbSessaoActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrediente:");

        jCmbIngrediente.setBackground(new java.awt.Color(102, 102, 255));
        jCmbIngrediente.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCmbIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        jCmbIngrediente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbIngredienteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbMes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jCmbSessao, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCmbIngrediente, 0, 210, Short.MAX_VALUE))
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jCmbMes)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCmbEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCmbSessao)
                    .addComponent(jLabel5)
                    .addComponent(jCmbIngrediente))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Persistencia
        DaoConsulta dC = new DaoConsulta();
        DaoIngrediente dI = new DaoIngrediente();
        DaoEntregador dE = new DaoEntregador();
    //Negocio
        List<Object> listaI = new ArrayList<>();
        List<Object> listaE = new ArrayList<>();
    //Interface 
        CustomCelulaJTable tdRenderer = new CustomCelulaJTable(1);
    //Variaveis de Controle
        boolean init = true;//Correção de bug...
        
    public void selecionarTipo(int op)//Ativa os comboBox de acordo com o tipo de consulta
    {
        switch(op)
        {
            case 1:
                jCmbMes.setEnabled(false);
                jCmbEntregador.setEnabled(false);
                jCmbSessao.setEnabled(false);
                jCmbIngrediente.setEnabled(false);
                break;
            case 2:
                jCmbMes.setEnabled(false);
                jCmbEntregador.setEnabled(false);
                jCmbSessao.setEnabled(true);
                jCmbIngrediente.setEnabled(false);
                break;
            case 3:
                jCmbMes.setEnabled(false);
                jCmbEntregador.setEnabled(false);
                jCmbSessao.setEnabled(false);
                jCmbIngrediente.setEnabled(true);
                break;
            case 4:
                jCmbMes.setEnabled(false);
                jCmbIngrediente.setEnabled(false);
                jCmbSessao.setEnabled(false);
                jCmbEntregador.setEnabled(true);
                break;
            case 5:
                jCmbIngrediente.setEnabled(false);
                jCmbEntregador.setEnabled(false);
                jCmbSessao.setEnabled(false);
                jCmbMes.setEnabled(true);
                break;
            case 6:
                jCmbMes.setEnabled(false);
                jCmbEntregador.setEnabled(false);
                jCmbSessao.setEnabled(false);
                jCmbIngrediente.setEnabled(false);
                break;
            case 7:
                jCmbMes.setEnabled(false);
                jCmbEntregador.setEnabled(false);
                jCmbSessao.setEnabled(false);
                jCmbIngrediente.setEnabled(false);
                break;
        }
    }
    public void customizeTable()//Coloca cor na tabela
    {
        for(int i = 0; i < jTblConsulta.getColumnModel().getColumnCount(); i++)
        {
            jTblConsulta.getColumnModel().getColumn(i).setCellRenderer(tdRenderer);
            jTblConsulta.getColumnModel().getColumn(i).setHeaderRenderer(new CustomCabecalhoJTable(1));
        }
        jTblConsulta.setCellSelectionEnabled(true);
        jTblConsulta.setSelectionBackground(Color.BLUE);
    }
    public void lookAndFeel()
    {
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrmConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrmConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrmConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrmConsulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblVoltarMouseClicked
    {//GEN-HEADEREND:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jCmbMesActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbMesActionPerformed
    {//GEN-HEADEREND:event_jCmbMesActionPerformed
        // TODO add your handling code here:
        int mes = jCmbMes.getSelectedIndex();
        if(mes == 0)
        {
            jTblConsulta.setModel(dC.retornaLista(5, ""));
        }
        else
        {
            jTblConsulta.setModel(dC.retornaLista(13, String.valueOf(mes)));
        }
        customizeTable();
    }//GEN-LAST:event_jCmbMesActionPerformed

    private void jCmbSessaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbSessaoActionPerformed
    {//GEN-HEADEREND:event_jCmbSessaoActionPerformed
        // TODO add your handling code here:
        int secao = jCmbSessao.getSelectedIndex();
        if(secao == 0)
        {
            jTblConsulta.setModel(dC.retornaLista(2, ""));
        }
        else
        {
            jTblConsulta.setModel(dC.retornaLista(9, (String)jCmbSessao.getSelectedItem()));
        }
        customizeTable();
    }//GEN-LAST:event_jCmbSessaoActionPerformed

    private void jCmbIngredienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbIngredienteActionPerformed
    {//GEN-HEADEREND:event_jCmbIngredienteActionPerformed
        // TODO add your handling code here:
        if(!init)
        {
            int ing = jCmbIngrediente.getSelectedIndex();
            if(ing == 0)
            {
                jTblConsulta.setModel(dC.retornaLista(3, ""));
            }
            else
            {
                Ingrediente i = (Ingrediente) listaI.get(ing - 1);
                jTblConsulta.setModel(dC.retornaLista(8, String.valueOf(i.getID())));
            }
            customizeTable();
        }
        
    }//GEN-LAST:event_jCmbIngredienteActionPerformed

    private void jCmbEntregadorActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbEntregadorActionPerformed
    {//GEN-HEADEREND:event_jCmbEntregadorActionPerformed
        // TODO add your handling code here:
        if(!init)
        {
            int entregador = jCmbEntregador.getSelectedIndex();
            if(entregador == 0)
            {
                jTblConsulta.setModel(dC.retornaLista(4, ""));
            }
            else
            {
                Entregador e = (Entregador) listaE.get(entregador -1);
                jTblConsulta.setModel(dC.retornaLista(11, String.valueOf(e.getID())));
            }
            customizeTable();
        }
    }//GEN-LAST:event_jCmbEntregadorActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        int posiI = jCmbIngrediente.getSelectedIndex();
        try
        {
           listaI = dI.carrega();
           jCmbIngrediente.removeAllItems();
           jCmbIngrediente.addItem("Todos");
           for(int ind=0; ind < listaI.size(); ind++) 
           {
               Object o = listaI.get(ind);
               Ingrediente i = (Ingrediente) o;
               jCmbIngrediente.addItem(i.getNome()); 
           }
           if (posiI > -1) 
             jCmbIngrediente.setSelectedIndex(posiI);
        } 
        catch(Exception e)
        {
            Diversos.mostrarDados("Problemas ao carregar, inexistência de ingredientes" +
                    e.getMessage(), "Another Roman Leader", false); 
            e.printStackTrace();
        }
        int posiE = jCmbEntregador.getSelectedIndex();
        try
        {
            listaE = dE.carrega();
            jCmbEntregador.removeAllItems();
            jCmbEntregador.addItem("Todos");
            for (int ind = 0; ind < listaE.size(); ind++)
            {
                Object o = listaE.get(ind);
                Entregador en = (Entregador) o;
                jCmbEntregador.addItem(en.getNome());
            }
            if (posiE > -1)
            {
                jCmbEntregador.setSelectedIndex(posiE);
            }
        } catch (Exception e)
        {
            Diversos.mostrarDados("Problemas ao carregar, inexistência de entregadores"
                    + e.getMessage(), "19:39", false);
            e.printStackTrace();
        }
        init = false;
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox jCmbEntregador;
    private javax.swing.JComboBox jCmbIngrediente;
    private javax.swing.JComboBox jCmbMes;
    private javax.swing.JComboBox jCmbSessao;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTblConsulta;
    // End of variables declaration//GEN-END:variables
}
