/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.pedroaugusto.mycomponents;

/**
 *
 * @author Pedro
 */
public class ASearchBox extends javax.swing.JPanel {

    /**
     * Creates new form ASearchBox
     */
    private Placeholder placeholder;
    public ASearchBox()
    {
        initComponents();
        placeholder = new Placeholder(field, "The world is treating me bad...Misery.", true);
    }
    
    public void setPlaceholder(String text)
    {
        placeholder.turnOn(text);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jLabel15 = new javax.swing.JLabel();
        field = new javax.swing.JTextField();

        setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(204, 204, 204)), javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 1, new java.awt.Color(102, 102, 102))));
        setPreferredSize(new java.awt.Dimension(841, 38));
        setLayout(new javax.swing.BoxLayout(this, javax.swing.BoxLayout.LINE_AXIS));

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/pedroaugusto/mycomponents/search.png"))); // NOI18N
        jLabel15.setBorder(javax.swing.BorderFactory.createEmptyBorder(7, 5, 7, 5));
        jLabel15.setOpaque(true);
        add(jLabel15);

        field.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        field.setForeground(new java.awt.Color(64, 64, 64));
        field.setText("Pesquisar cliente");
        field.setBorder(javax.swing.BorderFactory.createEmptyBorder(3, 3, 3, 3));
        field.setMinimumSize(new java.awt.Dimension(6, 38));
        field.setPreferredSize(new java.awt.Dimension(136, 38));
        add(field);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField field;
    private javax.swing.JLabel jLabel15;
    // End of variables declaration//GEN-END:variables
}
