/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.GerenteView;

import Negocio.Diversos;
import Negocio.Estoque;

/**
 *
 * @author Pedro
 */
public class JDialogEstoque extends javax.swing.JDialog {

    /** Creates new form JDialogEstoque
     * @param parent
     * @param modal
     * @param telaIngrediente
     * @param nome
     * @param uni */
    public JDialogEstoque(java.awt.Frame parent, boolean modal, JFrmIngrediente telaIngrediente,
            String nome, String uni) {
        super(parent, modal);
        setLookAndFeel();
        initComponents();
        this.telaIngrediente = telaIngrediente;
        this.nome = nome;
        this.uni = uni;
        if(this.telaIngrediente.getEstoque() == null)
        {
            jTxtProduto.setText(nome);
            jLblUni.setText(uni);
            jLblUni2.setText(uni);
            jLblUni3.setText(uni);
        }
        else
        {
            carregarObjeto(telaIngrediente.getEstoque());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtEstoqueMax = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtEstoqueAtual = new javax.swing.JTextField();
        jLblUni2 = new javax.swing.JLabel();
        jLblUni3 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLblUni = new javax.swing.JLabel();
        jLblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jTxtEstoqueMin = new javax.swing.JTextField();
        jTxtProduto = new javax.swing.JTextField();
        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnAlterar = new javax.swing.JButton();
        jLblVoltar = new javax.swing.JLabel();
        jLblLimpar = new javax.swing.JLabel();

        jScrollPane1.setViewportView(jTextPane1);

        jScrollPane2.setViewportView(jTextPane2);

        jScrollPane3.setViewportView(jTextPane3);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("August- Estoque");
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(22, 73, 154));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 153, 51)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Estoque Minimo:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Estoque Maximo:");

        jTxtEstoqueMax.setBackground(new java.awt.Color(102, 102, 255));
        jTxtEstoqueMax.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtEstoqueMax.setForeground(new java.awt.Color(255, 255, 255));
        jTxtEstoqueMax.setText("0");
        jTxtEstoqueMax.setToolTipText("Somente inteiros");
        jTxtEstoqueMax.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtEstoqueMax.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTxtEstoqueMaxKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Estoque Atual:");

        jTxtEstoqueAtual.setEditable(false);
        jTxtEstoqueAtual.setBackground(new java.awt.Color(102, 102, 255));
        jTxtEstoqueAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtEstoqueAtual.setForeground(new java.awt.Color(255, 255, 255));
        jTxtEstoqueAtual.setText("0");
        jTxtEstoqueAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        jLblUni2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblUni2.setForeground(new java.awt.Color(255, 255, 255));
        jLblUni2.setText("KG");

        jLblUni3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblUni3.setForeground(new java.awt.Color(255, 255, 255));
        jLblUni3.setText("KG");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Produto:");

        jLblUni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblUni.setForeground(new java.awt.Color(255, 255, 255));
        jLblUni.setText("KG");

        jLblTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setText("Estoque");

        jTxtEstoqueMin.setBackground(new java.awt.Color(102, 102, 255));
        jTxtEstoqueMin.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtEstoqueMin.setForeground(new java.awt.Color(255, 255, 255));
        jTxtEstoqueMin.setText("0");
        jTxtEstoqueMin.setToolTipText("Somente inteiros");
        jTxtEstoqueMin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtEstoqueMin.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTxtEstoqueMinKeyReleased(evt);
            }
        });

        jTxtProduto.setEditable(false);
        jTxtProduto.setBackground(new java.awt.Color(102, 102, 255));
        jTxtProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtProduto.setForeground(new java.awt.Color(255, 255, 255));
        jTxtProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        Logo.setBackground(new java.awt.Color(22, 73, 154));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/c5.png"))); // NOI18N

        jLabel17.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setText("August");

        org.jdesktop.layout.GroupLayout LogoLayout = new org.jdesktop.layout.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(LogoLayout.createSequentialGroup()
                .add(jLabel17)
                .add(2, 2, 2)
                .add(jLabel1)
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLabel1)
            .add(jLabel17, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
        );

        jPnlBotoes.setBackground(new java.awt.Color(22, 73, 154));

        jBtnAlterar.setBackground(new java.awt.Color(102, 102, 255));
        jBtnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setBorderPainted(false);
        jBtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jLblVoltar.setBackground(new java.awt.Color(204, 0, 0));
        jLblVoltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jLblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVoltar.setText("←");
        jLblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblVoltarMouseClicked(evt);
            }
        });

        jLblLimpar.setBackground(new java.awt.Color(204, 0, 0));
        jLblLimpar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jLblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/limpar2.png"))); // NOI18N
        jLblLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblLimpar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblLimparMouseClicked(evt);
            }
        });

        org.jdesktop.layout.GroupLayout jPnlBotoesLayout = new org.jdesktop.layout.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPnlBotoesLayout.createSequentialGroup()
                .add(jLblVoltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(146, 146, 146)
                .add(jBtnAlterar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 214, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(jLblLimpar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 40, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .add(jBtnAlterar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 28, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .add(0, 0, Short.MAX_VALUE)
                .add(jPnlBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLblVoltar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLblLimpar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
        );

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(12, 12, 12)
                                .add(jLblTitulo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(32, 32, 32)
                        .add(Logo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(12, 12, 12)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jLabel14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jTxtProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                            .add(jPanel1Layout.createSequentialGroup()
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                        .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jTxtEstoqueMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 216, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, jPanel1Layout.createSequentialGroup()
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 161, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(jTxtEstoqueMax)
                                            .add(jTxtEstoqueAtual))))
                                .add(6, 6, 6)
                                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLblUni)
                                    .add(jLblUni2)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLblUni3))))))
                .addContainerGap(117, Short.MAX_VALUE))
            .add(jPnlBotoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(jLblTitulo)
                        .add(0, 0, 0)
                        .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(Logo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 56, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel14)
                    .add(jTxtProduto, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(16, 16, 16)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel2)
                    .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                        .add(jLblUni)
                        .add(jTxtEstoqueMin, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel5)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtEstoqueMax, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLblUni2))))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(2, 2, 2)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                            .add(jTxtEstoqueAtual, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 25, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jLblUni3))))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPnlBotoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Persistencia
        
    //Negocio
    
    //Interface
    
    //Variaveis de Controle
        JFrmIngrediente telaIngrediente;//Tela que contem o metodo setEstoque
        String nome, uni;//Variaveis nome e unidade de um novo ingrediente
        
    public void limpar()
    {
        jTxtEstoqueMin.setText("");
        jTxtEstoqueMax.setText("");
    }
    public void carregarObjeto(Estoque e)
    {
        jTxtProduto.setText(nome);
        jTxtEstoqueMin.setText(String.valueOf(e.getEstoqueMinimo()));
        jTxtEstoqueMax.setText(String.valueOf(e.getEstoqueMaximo()));
        jTxtEstoqueAtual.setText(String.valueOf(e.getEstoqueAtual()));
        jLblUni.setText(uni);
        jLblUni2.setText(uni);
        jLblUni3.setText(uni);
    }
    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAlterarActionPerformed
    {//GEN-HEADEREND:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        Estoque e;
        if(!jTxtProduto.getText().isEmpty()
            && !jTxtEstoqueMin.getText().isEmpty()
            && !jTxtEstoqueAtual.getText().isEmpty()
            && !jTxtEstoqueMax.getText().isEmpty()
        )
        {
            e = new Estoque();
            e.setEstoqueAtual(Float.parseFloat(jTxtEstoqueAtual.getText()));
            e.setEstoqueMinimo(Integer.parseInt(jTxtEstoqueMin.getText()));
            e.setEstoqueMaximo(Integer.parseInt(jTxtEstoqueMax.getText()));
            telaIngrediente.setEstoque(e);
            dispose();
        }
        else
        {
            Diversos.mostrarDados("Preencha todos os campos", "I am the eggman", false);
        }
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblVoltarMouseClicked
    {//GEN-HEADEREND:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jLblLimparMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblLimparMouseClicked
    {//GEN-HEADEREND:event_jLblLimparMouseClicked
        limpar();
    }//GEN-LAST:event_jLblLimparMouseClicked

    private void jTxtEstoqueMinKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtEstoqueMinKeyReleased
    {//GEN-HEADEREND:event_jTxtEstoqueMinKeyReleased
        // TODO add your handling code here:
        jTxtEstoqueMin.setText(Diversos.testaNum(jTxtEstoqueMin.getText(), 2));
    }//GEN-LAST:event_jTxtEstoqueMinKeyReleased

    private void jTxtEstoqueMaxKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtEstoqueMaxKeyReleased
    {//GEN-HEADEREND:event_jTxtEstoqueMaxKeyReleased
        // TODO add your handling code here:
        jTxtEstoqueMax.setText(Diversos.testaNum(jTxtEstoqueMax.getText(), 2));
    }//GEN-LAST:event_jTxtEstoqueMaxKeyReleased
    public void setLookAndFeel()
    {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDialogEstoque.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblLimpar;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLblUni;
    private javax.swing.JLabel jLblUni2;
    private javax.swing.JLabel jLblUni3;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane jTextPane2;
    private javax.swing.JTextPane jTextPane3;
    private javax.swing.JTextField jTxtEstoqueAtual;
    private javax.swing.JTextField jTxtEstoqueMax;
    private javax.swing.JTextField jTxtEstoqueMin;
    private javax.swing.JTextField jTxtProduto;
    // End of variables declaration//GEN-END:variables

}
