/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.GerenteView;

/**
 *
 * @author aluno
 */
import Interface.GerenteView.FileBox;
import Negocio.Diversos;
import Negocio.Entregador;
import Persistencia.DaoEntregador;
import java.awt.Image;
import java.io.File;
import java.text.NumberFormat;
import javax.swing.ImageIcon;
public class JFrmEntregador extends javax.swing.JFrame {

    /**
     * Creates new form JFrmEntregador
     */
    public JFrmEntregador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLblFoto = new javax.swing.JLabel();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jLblVoltar = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jLblLimpar = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jTxtSalario = new javax.swing.JTextField();
        jFtdTxtData = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jCmbVeiculo = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jFtdTxtCPF = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("August- Controle Entregador");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(22, 73, 154));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jLblFoto.setFont(new java.awt.Font("DejaVu Sans", 0, 18)); // NOI18N
        jLblFoto.setForeground(new java.awt.Color(254, 254, 254));
        jLblFoto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblFoto.setText("CARREGAR IMG");
        jLblFoto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(253, 251, 251)));
        jLblFoto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblFoto.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblFotoMouseClicked(evt);
            }
        });

        jPnlBotoes.setBackground(new java.awt.Color(22, 73, 154));

        jBtnIncluir.setBackground(new java.awt.Color(102, 102, 255));
        jBtnIncluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnIncluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.setBorderPainted(false);
        jBtnIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setBackground(new java.awt.Color(102, 102, 255));
        jBtnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setBorderPainted(false);
        jBtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jLblVoltar.setBackground(new java.awt.Color(204, 0, 0));
        jLblVoltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jLblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVoltar.setText("←");
        jLblVoltar.setToolTipText("Voltar");
        jLblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblVoltarMouseClicked(evt);
            }
        });

        jBtnExcluir.setBackground(new java.awt.Color(102, 102, 255));
        jBtnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setBorderPainted(false);
        jBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLblLimpar.setBackground(new java.awt.Color(204, 0, 0));
        jLblLimpar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jLblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/limpar2.png"))); // NOI18N
        jLblLimpar.setToolTipText("Limpar");
        jLblLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblLimpar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addComponent(jLblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addComponent(jBtnIncluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addComponent(jLblLimpar))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblLimpar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID:");

        jTxtID.setBackground(new java.awt.Color(102, 102, 255));
        jTxtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtID.setForeground(new java.awt.Color(255, 255, 255));
        jTxtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtID.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtIDFocusLost(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nome:");

        jTxtNome.setBackground(new java.awt.Color(102, 102, 255));
        jTxtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtNome.setForeground(new java.awt.Color(255, 255, 255));
        jTxtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Salario:");

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Nascimento:");

        jTxtSalario.setBackground(new java.awt.Color(102, 102, 255));
        jTxtSalario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtSalario.setForeground(new java.awt.Color(255, 255, 255));
        jTxtSalario.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        jFtdTxtData.setBackground(new java.awt.Color(102, 102, 255));
        jFtdTxtData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jFtdTxtData.setForeground(new java.awt.Color(255, 255, 255));
        jFtdTxtData.setFormatterFactory(Diversos.FormatoMascara(1));
        jFtdTxtData.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Veiculo:");

        jCmbVeiculo.setBackground(new java.awt.Color(102, 102, 255));
        jCmbVeiculo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCmbVeiculo.setForeground(new java.awt.Color(255, 255, 255));
        jCmbVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Moto", "Bike", "Carro" }));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("CPF:");

        jFtdTxtCPF.setBackground(new java.awt.Color(102, 102, 255));
        jFtdTxtCPF.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jFtdTxtCPF.setForeground(new java.awt.Color(255, 255, 255));
        jFtdTxtCPF.setFormatterFactory(Diversos.FormatoMascara(2));
        jFtdTxtCPF.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNome)
                    .addComponent(jTxtID)
                    .addComponent(jTxtSalario)
                    .addComponent(jFtdTxtData)
                    .addComponent(jCmbVeiculo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jFtdTxtCPF))
                .addGap(126, 126, 126))
            .addComponent(jPnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTxtSalario, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(jFtdTxtData, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(jCmbVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jFtdTxtCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jLblFoto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Persistencia
        DaoEntregador dE = new DaoEntregador();
    //Negocio
        
    //Interface
        
    //Variaveis de Controle
        String url = "";//URL da img usada
        final String titulo = "August";
    
    public void carregarObjeto(Entregador e)
    {
        
        jTxtID.setText(String.valueOf(e.getID()));
        jTxtNome.setText(e.getNome());
        jTxtSalario.setText(NumberFormat.getCurrencyInstance().format(e.getSalario()));
        jFtdTxtData.setText(e.getDataNascimento());
        String a = (String) e.getVeiculo();//Ué
        jCmbVeiculo.setSelectedItem(a);
        jFtdTxtCPF.setText(e.getCpf());
        if(!e.getFotoURL().equals("blue jay way"))//Não tem foto
        {
            if(new File(e.getFotoURL()).exists())
                jLblFoto.setIcon(toScala(new ImageIcon(e.getFotoURL())));
            else
                Diversos.mostrarDados(e.getFotoURL()+"\nNão encontrado", titulo, false);
        }
        else
        {
            jLblFoto.setText("CARREGAR IMG");
        }
    }    
    public void limpar()
    {
        jTxtID.setText("");
        jTxtID.requestFocusInWindow();
        jTxtID.setEditable(true);
        jTxtNome.setText("");
        jTxtSalario.setText("");
        jFtdTxtData.setText("");
        jCmbVeiculo.setSelectedIndex(-1);
        jFtdTxtCPF.setText("");
        jLblFoto.setIcon(null);
        jLblFoto.setText("CARREGAR IMG");
        jTxtID.setEditable(true);
        jBtnIncluir.setEnabled(false);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        url = "";
    }
    public void changeFoto(String url)//Troca o icone do jLabel
    {
        this.url = url;
        jLblFoto.setText((""));
        ImageIcon icone = new javax.swing.ImageIcon(url);
        jLblFoto.setIcon(toScala(icone));
    }
    public ImageIcon toScala(ImageIcon ico)//Coloca a imgagem na escala a apropriada
    {
        Image img = ico.getImage().getScaledInstance(205, 200, 1);
        return new ImageIcon(img);
    }
    private void jLblFotoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblFotoMouseClicked
        if(Diversos.HABILITAR)//Verifica se a edicao de imagem esta habilitada
        {
            new FileBox(this).setVisible(true);
        }
        else
        {
            Diversos.mostrarDados("Edição desabilitada!\nHabilite na tela inicial", titulo, true);
        }
    }//GEN-LAST:event_jLblFotoMouseClicked

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Entregador e;
        int id;
        if(!jTxtID.getText().isEmpty()
            && jCmbVeiculo.getSelectedIndex() > -1
            && !jTxtNome.getText().isEmpty()
            && !jTxtSalario.getText().isEmpty()
            && !jFtdTxtData.getText().isEmpty()
        )
        {
            e = new Entregador();
            e.setID(Integer.parseInt(jTxtID.getText()));
            e.setNome(jTxtNome.getText());
            e.setVeiculo((String)jCmbVeiculo.getSelectedItem());
            e.setDataNascimento(jFtdTxtData.getText());
            e.setFotoURL((url.isEmpty() ? "blue jay way" : url));
            String preco = jTxtSalario.getText().replace(",", ".");
            preco = preco.replace("R$ ", "");
            try{
                e.setSalario(Float.parseFloat(preco));
            }catch(Exception ex){
                Diversos.mostrarDados("Nao converteu o preco. Tire as virgulas", titulo, false);
                return;
            }
            e.setCpf(jFtdTxtCPF.getText());
            if(jBtnIncluir.isEnabled())
            {
                if (dE.incluir(e))
                { //==true
                    Diversos.mostrarDados("Entregador foi inserido com sucesso", "hey you", true);
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
                }
                else // ==false
                {
                    Diversos.mostrarDados("Problemas ao inserir os dados do entregador)", titulo, false);
                }
            }
            else
            {
                if(dE.alterar(e))
                {
                    Diversos.mostrarDados("Dados do entregador foram atualizados com sucesso", titulo, true);
                }
                else
                {
                    Diversos.mostrarDados("Problemas ao atualizar os dados do entregador", titulo, false);
                    jBtnAlterar.setEnabled(false);
                    jBtnIncluir.setEnabled(false);
                }
            }
            jBtnIncluir.setEnabled(false);
        }
        else
        {
            Diversos.mostrarDados("Preencha todos os campos", "The Blue Box", false);
        }
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        jBtnIncluirActionPerformed(evt);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Diversos.confirmar("Deseja excluir?", "knock knock"))
        {
            int existem = dE.verificaChave(Integer.parseInt(jTxtID.getText()));
            if (existem > 0)
            {
                if(Diversos.confirmar("Esse entregador esta presente em: "
                        + ""+existem+" pedidos.\nDeseja realmente excluir?", titulo))
                if(dE.excluir(Integer.parseInt(jTxtID.getText()), 0))
                {
                    Diversos.mostrarDados("Entregador foi excluido com sucesso", titulo, true);
                    limpar();
                    jBtnAlterar.setEnabled(false);
                    jBtnExcluir.setEnabled(false);
                } 
                else
                {
                    Diversos.mostrarDados("Problemas ao excluir um entregador ", "Why? Tell me Why.", false);
                }
            }
            else
            {
                if(dE.excluir(Integer.parseInt(jTxtID.getText()), 0))
                {
                    Diversos.mostrarDados("Entregador foi excluido com sucesso", titulo, true);
                    limpar();
                    jBtnAlterar.setEnabled(false);
                    jBtnExcluir.setEnabled(false);
                } 
                else
                {
                    Diversos.mostrarDados("Problemas ao excluir um entregador ", "Why? Tell me Why.", false);
                }
            }
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTxtIDFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTxtIDFocusLost
        // TODO add your handling code here:
        Entregador e = null;
        int id;
        if(!Diversos.testaNum(jTxtID.getText(), titulo))
        {
            jTxtID.setText("");
            jTxtID.requestFocusInWindow();
        }
        else
        {
            id = Integer.parseInt(jTxtID.getText());
            if(!Diversos.intervalo(id, 0, 0, titulo))
            {
                jTxtID.setText("");
                jTxtID.requestFocusInWindow();
            }
            else
            {
                e = dE.busca(id, 0);
                if (e == null)
                {
                    jBtnIncluir.setEnabled(true);
                    Diversos.mostrarDados("Entregador inexistente", "Pepperland", false);
                }
                else
                {
                    carregarObjeto(e);
                    url = e.getFotoURL();
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
                }
            }
            jTxtID.setEditable(false);
        }
    }//GEN-LAST:event_jTxtIDFocusLost

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_formWindowOpened

    private void jLblLimparMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLblLimparMouseClicked
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jLblLimparMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmEntregador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JComboBox jCmbVeiculo;
    private javax.swing.JFormattedTextField jFtdTxtCPF;
    private javax.swing.JFormattedTextField jFtdTxtData;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLblFoto;
    private javax.swing.JLabel jLblLimpar;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtSalario;
    // End of variables declaration//GEN-END:variables
}
