/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AtendenteView;

/**
 *
 * @author Pedro
 */
import Interface.CustomizarTabela.CustomCelulaJTable;
import Negocio.Diversos;
import Negocio.Endereco;
import Negocio.Entregador;
import Negocio.Ingrediente;
import Negocio.Pedido;
import Negocio.Prato;
import Persistencia.DaoEntregador;
import Persistencia.DaoIngrediente;
import Persistencia.DaoLote;
import Persistencia.DaoPedido;
import Persistencia.DaoPrato;
import java.awt.Color;
import java.text.DateFormat;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

public class JFrmPedido extends javax.swing.JFrame
{

    /**
     * Creates new form JFrmPedido
     */
    public JFrmPedido()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTxtNomeCliente = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jFtdTxtTelefone = new javax.swing.JFormattedTextField();
        jLabel18 = new javax.swing.JLabel();
        jCmbFormaPagamento = new javax.swing.JComboBox();
        jLabel19 = new javax.swing.JLabel();
        jBtnTravar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jFtdTxtData = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jCmbEntregadorNome = new javax.swing.JComboBox();
        jLabel21 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLblSenha = new javax.swing.JLabel();
        jBtnGerar = new javax.swing.JButton();
        jBtnEndereco = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jLblVoltar = new javax.swing.JLabel();
        jLblLimpar = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblPratosAdd = new javax.swing.JTable();
        jLabel23 = new javax.swing.JLabel();
        jTxtBuscaPratos = new javax.swing.JTextField();
        jBtnAdicionar = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jLstPratosEncontrados = new javax.swing.JList();
        jLabel24 = new javax.swing.JLabel();
        jTxtTotal = new javax.swing.JTextField();
        jLblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPnlInfo = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLblStatus = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLblTempoDecorrido = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pediddo");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(22, 73, 154));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(102, 102, 255), new java.awt.Color(102, 102, 102)));

        Logo.setBackground(new java.awt.Color(22, 75, 154));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cr2.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("August");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addGroup(LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID:");

        jTxtID.setBackground(new java.awt.Color(102, 102, 255));
        jTxtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtID.setForeground(new java.awt.Color(255, 255, 255));
        jTxtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtID.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtIDFocusLost(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Nome Cliente:");

        jTxtNomeCliente.setBackground(new java.awt.Color(102, 102, 255));
        jTxtNomeCliente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtNomeCliente.setForeground(new java.awt.Color(255, 255, 255));
        jTxtNomeCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Telefone:");

        jFtdTxtTelefone.setBackground(new java.awt.Color(102, 102, 255));
        jFtdTxtTelefone.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jFtdTxtTelefone.setForeground(new java.awt.Color(255, 255, 255));
        jFtdTxtTelefone.setFormatterFactory(Diversos.FormatoMascara(3));
        jFtdTxtTelefone.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Forma Pagamento:");

        jCmbFormaPagamento.setBackground(new java.awt.Color(102, 102, 255));
        jCmbFormaPagamento.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCmbFormaPagamento.setForeground(new java.awt.Color(255, 255, 255));
        jCmbFormaPagamento.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Cartão", "Dinheiro", "Ticket", "Allons-y!" }));

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Data:");

        jBtnTravar.setBackground(new java.awt.Color(102, 102, 255));
        jBtnTravar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnTravar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnTravar.setText("Travar");
        jBtnTravar.setToolTipText("Travar hora(opcional)");
        jBtnTravar.setBorderPainted(false);
        jBtnTravar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnTravarActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jFtdTxtData.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jFtdTxtData.setForeground(new java.awt.Color(255, 255, 255));
        jFtdTxtData.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFtdTxtData, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jFtdTxtData, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Entregador:");

        jCmbEntregadorNome.setBackground(new java.awt.Color(102, 102, 255));
        jCmbEntregadorNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCmbEntregadorNome.setForeground(new java.awt.Color(255, 255, 255));

        jLabel21.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Senha:");

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLblSenha.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLblSenha.setForeground(new java.awt.Color(255, 255, 255));
        jLblSenha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLblSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
        );

        jBtnGerar.setBackground(new java.awt.Color(102, 102, 255));
        jBtnGerar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnGerar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnGerar.setText("Gerar");
        jBtnGerar.setToolTipText("Gerar senha aleatória");
        jBtnGerar.setBorderPainted(false);
        jBtnGerar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnGerarActionPerformed(evt);
            }
        });

        jBtnEndereco.setBackground(new java.awt.Color(102, 102, 255));
        jBtnEndereco.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnEndereco.setForeground(new java.awt.Color(255, 255, 255));
        jBtnEndereco.setText("Endereço");
        jBtnEndereco.setToolTipText("Selecione o endereço");
        jBtnEndereco.setBorderPainted(false);
        jBtnEndereco.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnEndereco.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnEnderecoActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Endereço:");

        jPnlBotoes.setBackground(new java.awt.Color(22, 73, 154));

        jBtnIncluir.setBackground(new java.awt.Color(102, 102, 255));
        jBtnIncluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnIncluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.setBorderPainted(false);
        jBtnIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setBackground(new java.awt.Color(102, 102, 255));
        jBtnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setBorderPainted(false);
        jBtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setBackground(new java.awt.Color(102, 102, 255));
        jBtnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setBorderPainted(false);
        jBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLblVoltar.setBackground(new java.awt.Color(204, 0, 0));
        jLblVoltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jLblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVoltar.setText("←");
        jLblVoltar.setToolTipText("Voltar");
        jLblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblVoltarMouseClicked(evt);
            }
        });

        jLblLimpar.setBackground(new java.awt.Color(204, 0, 0));
        jLblLimpar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jLblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/limpar2.png"))); // NOI18N
        jLblLimpar.setToolTipText("Limpar");
        jLblLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblLimpar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addComponent(jLblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir)
                .addGap(45, 45, 45)
                .addComponent(jLblLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(322, Short.MAX_VALUE))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel4.setBackground(new java.awt.Color(22, 73, 154));

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jTblPratosAdd.setBackground(new java.awt.Color(102, 102, 255));
        jTblPratosAdd.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Nº", "Prato"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTblPratosAdd.setGridColor(new java.awt.Color(234, 234, 234));
        jTblPratosAdd.setRowHeight(25);
        jTblPratosAdd.setShowHorizontalLines(false);
        jTblPratosAdd.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTblPratosAdd);
        if (jTblPratosAdd.getColumnModel().getColumnCount() > 0)
        {
            jTblPratosAdd.getColumnModel().getColumn(0).setCellRenderer(tdRenderer);
            jTblPratosAdd.getColumnModel().getColumn(1).setCellRenderer(tdRenderer);
        }
        if (jTblPratosAdd.getColumnModel().getColumnCount() > 0)
        {
            jTblPratosAdd.getColumnModel().getColumn(0).setHeaderRenderer(new Interface.CustomizarTabela.CustomCabecalhoJTable(1));
            jTblPratosAdd.getColumnModel().getColumn(1).setHeaderRenderer(new Interface.CustomizarTabela.CustomCabecalhoJTable(1));
        }

        jScrollPane2.getViewport().setBackground(new Color(102,102,255));

        jLabel23.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Prato:");

        jTxtBuscaPratos.setBackground(new java.awt.Color(102, 102, 255));
        jTxtBuscaPratos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtBuscaPratos.setForeground(new java.awt.Color(255, 255, 255));
        jTxtBuscaPratos.setToolTipText("Caixa de pesquisa por incial");
        jTxtBuscaPratos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtBuscaPratos.setName("NomeField"); // NOI18N
        jTxtBuscaPratos.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtBuscaPratosFocusLost(evt);
            }
        });
        jTxtBuscaPratos.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTxtBuscaPratosKeyReleased(evt);
            }
        });

        jBtnAdicionar.setBackground(new java.awt.Color(102, 102, 255));
        jBtnAdicionar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnAdicionar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAdicionar.setText("Add");
        jBtnAdicionar.setToolTipText("Adiciona um prato a tabela");
        jBtnAdicionar.setBorderPainted(false);
        jBtnAdicionar.setEnabled(false);
        jBtnAdicionar.setName("AddButton"); // NOI18N
        jBtnAdicionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAdicionarActionPerformed(evt);
            }
        });

        jScrollPane3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(22, 73, 154)));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jLstPratosEncontrados.setBackground(new java.awt.Color(22, 74, 154));
        jLstPratosEncontrados.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLstPratosEncontrados.setForeground(new java.awt.Color(255, 255, 255));
        jLstPratosEncontrados.setModel(new DefaultListModel());
        jLstPratosEncontrados.setName("PratosList"); // NOI18N
        jLstPratosEncontrados.addListSelectionListener(new javax.swing.event.ListSelectionListener()
        {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt)
            {
                jLstPratosEncontradosValueChanged(evt);
            }
        });
        jLstPratosEncontrados.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jLstPratosEncontradosFocusLost(evt);
            }
        });
        jScrollPane3.setViewportView(jLstPratosEncontrados);

        jLabel24.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Preço Total:");

        jTxtTotal.setEditable(false);
        jTxtTotal.setBackground(new java.awt.Color(102, 102, 255));
        jTxtTotal.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtTotal.setForeground(new java.awt.Color(255, 255, 255));
        jTxtTotal.setToolTipText("Soma de todos pratos do pedido");
        jTxtTotal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 294, Short.MAX_VALUE)
                    .addComponent(jTxtBuscaPratos))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAdicionar)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtTotal))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtBuscaPratos, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAdicionar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(jTxtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLblTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setText("Pedido");

        jPnlInfo.setBackground(new java.awt.Color(22, 73, 154));
        jPnlInfo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jPnlInfo.setForeground(new java.awt.Color(255, 255, 255));

        jLabel4.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Status:");

        jLblStatus.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLblStatus.setForeground(new java.awt.Color(0, 255, 0));
        jLblStatus.setText("Concluído");

        jLabel6.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Tempo:");

        jLblTempoDecorrido.setFont(new java.awt.Font("Lucida Bright", 1, 12)); // NOI18N
        jLblTempoDecorrido.setForeground(new java.awt.Color(204, 255, 255));
        jLblTempoDecorrido.setText("06:07:42");

        javax.swing.GroupLayout jPnlInfoLayout = new javax.swing.GroupLayout(jPnlInfo);
        jPnlInfo.setLayout(jPnlInfoLayout);
        jPnlInfoLayout.setHorizontalGroup(
            jPnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlInfoLayout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblTempoDecorrido, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jPnlInfoLayout.setVerticalGroup(
            jPnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel4)
                .addComponent(jLblStatus)
                .addComponent(jLabel6)
                .addComponent(jLblTempoDecorrido))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jFtdTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnTravar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbFormaPagamento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jCmbEntregadorNome, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jBtnEndereco, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jBtnGerar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(168, 168, 168)
                .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(183, 183, 183))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPnlInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel16)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTxtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jFtdTxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jCmbFormaPagamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(jLabel19))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnTravar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(jCmbEntregadorNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel21)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jBtnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBtnEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22)))
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 973, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Persistencia
            DaoPrato dP = new DaoPrato();
            DaoPedido dPE = new DaoPedido();
            DaoEntregador dE = new DaoEntregador();
            DaoLote dL = new DaoLote();
    
    //Negocio
            List<Object> lista = new ArrayList<>();
            List<Prato> pratos = new ArrayList<>();
            List<Prato> nomes;  
    //Interface
        CustomCelulaJTable tdRenderer = new CustomCelulaJTable(1);
        DefaultTableModel mod;
    
    //Variaveis de Controle
        int cont = 0;//Contador de colunas da tabela(desc...)
        float preco = 0;//Soma de todos os pratos no pedido
        static Thread rel;//Thread do relogio
        static boolean go = true;//Saída da thread do relogio
        static boolean go2 = true;//Saída da thread do tempo decorrido
        String titulo = "August";//Titulo 
        public Endereco endereco = null;//Dados do endereco do pedido

    public Endereco getEndereco()
    {
        return endereco;
    }

    public void setEndereco(Endereco e)
    {
        this.endereco = e;
    }

    public void limparListPratosEncontrados()
    {
        jLstPratosEncontrados.setBorder(null);
        jLstPratosEncontrados.setBackground(new Color(22, 73, 154));
        jBtnAdicionar.setEnabled(false);
        DefaultListModel listaModelo = (DefaultListModel) jLstPratosEncontrados.getModel();
        listaModelo.removeAllElements();
    }

    public void clearTable()
    {
        mod = (DefaultTableModel) jTblPratosAdd.getModel();
        for (int i = mod.getRowCount(); i > 0; i--)
        {
            mod.removeRow(i - 1);
        }
    }

    public void limpar()
    {
        jTxtID.setText("");
        jTxtID.setEditable(true);
        jTxtNomeCliente.setText("");
        jFtdTxtTelefone.setText("");
        jCmbFormaPagamento.setSelectedIndex(-1);
        jCmbEntregadorNome.setSelectedIndex(-1);
        jLblSenha.setText("");
        jLblStatus.setText("");
        jLblTempoDecorrido.setText("");
        jPnlInfo.setVisible(false);
        jTxtID.requestFocusInWindow();
        setEndereco(null);
        jTxtTotal.setText("");
        pratos.clear();
        cont = 0;
        clearTable();
        jBtnIncluir.setEnabled(false);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jBtnTravar.setEnabled(false);
        jBtnGerar.setEnabled(false);
        preco = 0;
        jBtnTravar.setText("Travar");
        go = true;
        relogio().start();
        go2 = false;
    }

    public void carregarObjeto(Pedido p)
    {
        //limpar();
        go = false;
        go2 = true;
        cont = p.getItens().size();
        preco = p.getValorTotal();
        jPnlInfo.setVisible(true);
        jLblTempoDecorrido.setText(String.valueOf(p.getTempoEntrega()));
        jTxtID.setText(String.valueOf(p.getID()));
        jTxtNomeCliente.setText(p.getNome());
        jFtdTxtTelefone.setText(p.getTel());
        jCmbFormaPagamento.setSelectedItem(p.getFormaPagamento());
        jFtdTxtData.setText(p.getData());
        jCmbEntregadorNome.setSelectedItem(p.getEntregador().getNome());
        jLblSenha.setText(String.valueOf(p.getSenha()));
        jTxtTotal.setText(NumberFormat.getCurrencyInstance().format(p.getValorTotal()));
        if (p.getStatus().equals("Em andamento"))
        {
            jLblStatus.setForeground(Color.YELLOW);
            tempoDecorrido(p.getData()).start();
        }else
        {
            jLblStatus.setForeground(Color.GREEN);
            jLblTempoDecorrido.setText(p.getTempoEntrega());//aki
        }
        jLblStatus.setText(p.getStatus());
        setEndereco(p.getEndereco());
        mod = (DefaultTableModel) jTblPratosAdd.getModel();
        pratos = p.getItens();
        for (int i = 0; i < p.getItens().size(); i++)//Carregando jtable
        {
            mod.addRow(new Object[]
            {
                i + 1, p.getItens().get(i).getNome()
            });
        }
    }
    private void jBtnTravarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnTravarActionPerformed
    {//GEN-HEADEREND:event_jBtnTravarActionPerformed
        // TODO add your handling code here:
        if (go == true)
        {
            go = false;
            jBtnTravar.setText("Contin");
        } else
        {
            go = true;
            relogio().start();
            jBtnTravar.setText("Travar");
        }
    }//GEN-LAST:event_jBtnTravarActionPerformed

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnIncluirActionPerformed
    {//GEN-HEADEREND:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Pedido p;
        int id;
        if (!jTxtID.getText().isEmpty()
                && !jTxtNomeCliente.getText().isEmpty()
                && !jFtdTxtTelefone.getText().isEmpty()
                && jCmbFormaPagamento.getSelectedIndex() > -1
                && jCmbEntregadorNome.getSelectedIndex() > -1
                && !jLblSenha.getText().isEmpty()
                && getEndereco() != null
                && !pratos.isEmpty())
        {
            p = new Pedido();
            id = Integer.parseInt((String) jTxtID.getText());
            p.setID(id);
            p.setNome(jTxtNomeCliente.getText());
            p.setTel(jFtdTxtTelefone.getText());
            p.setFormaPagamento(jCmbFormaPagamento.getSelectedItem().toString());
            p.setData(jFtdTxtData.getText());
            p.setEntregador((Entregador) lista.get(jCmbEntregadorNome.getSelectedIndex()));
            p.setSenha(Integer.parseInt(jLblSenha.getText()));
            p.setEndereco(getEndereco());
            p.setItens(pratos);
            p.setStatus("Em andamento");//Isso nao vai para alterar
            String preco = jTxtTotal.getText().replace(",", ".");
            preco = preco.replace("R$ ", "");
            p.setValorTotal(Float.parseFloat(preco));
            if(jBtnIncluir.isEnabled())
            {
                if (dL.verificarEstoque(p))
                {
                    if (dPE.incluir(p))
                    { //==true
                        Diversos.mostrarDados("Dados do pedido foram inseridos com sucesso", titulo, true);
                        jBtnAlterar.setEnabled(true);
                        jBtnExcluir.setEnabled(true);
                        for (int i = 0; i < p.getItens().size(); i++)//Dar baixa no estoque das coisas que sairam
                        {
                            Prato prato = p.getItens().get(i);
                            for (int j = 0; j < prato.getIngrediente().size(); j++)
                            {
                                Ingrediente en = prato.getIngrediente().get(j);
                                Float quant = prato.getQuantidade(j);
                                dL.atualizarEstoque("out", quant, dL.getCurrentLote(en, quant));
                            }
                        }
                    } 
                    else
                    {
                        Diversos.mostrarDados("Problemas ao inserir os dados do pedido)", titulo, false);
                    }
                }
            }
            else
            {
                if (dPE.alterar(p))
                {
                    String a = "Com que sucesso? Foi normal'-'";
                    Diversos.mostrarDados("Dados do pedido foram atualizados com sucesso", a, true);
                } else
                {
                    Diversos.mostrarDados("Problemas ao atualizar os dados do pedido", titulo, false);
                    jBtnAlterar.setEnabled(false);
                    jBtnIncluir.setEnabled(false);
                }
            }
            jBtnIncluir.setEnabled(false);
        } 
        else
        {
            Diversos.mostrarDados("Preencha todos os campos", "Doctor Robert", false);
        }
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAlterarActionPerformed
    {//GEN-HEADEREND:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        jBtnIncluirActionPerformed(evt);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnExcluirActionPerformed
    {//GEN-HEADEREND:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Diversos.confirmar("Deseja excluir?", "Let It Be"))
        {
            if (dPE.excluir(Integer.parseInt(jTxtID.getText()), 0))
            {
                Diversos.mostrarDados("Pedido foi excluido com sucesso", titulo, true);
                limpar();
                jBtnAlterar.setEnabled(false);
                jBtnExcluir.setEnabled(false);
            } else
            {
                Diversos.mostrarDados("Problemas ao excluir pedido", titulo, false);
            }
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblVoltarMouseClicked
    {//GEN-HEADEREND:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        go2 = false;
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jLblLimparMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblLimparMouseClicked
    {//GEN-HEADEREND:event_jLblLimparMouseClicked
        limpar();
    }//GEN-LAST:event_jLblLimparMouseClicked

    private void jTxtBuscaPratosKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtBuscaPratosKeyReleased
    {//GEN-HEADEREND:event_jTxtBuscaPratosKeyReleased
        // TODO add your handling code here:
        jBtnAdicionar.setEnabled(true);
        DefaultListModel listaModelo = (DefaultListModel) jLstPratosEncontrados.getModel();//Model da list
        listaModelo.removeAllElements();//Limpar list
        jTxtBuscaPratos.setText(jTxtBuscaPratos.getText().replace("'", ""));//Caractere ' não e permitido(...)!
        if (!jTxtBuscaPratos.getText().isEmpty())
        {
            nomes = dP.pesquisa(jTxtBuscaPratos.getText());//Devolve uma lista de pratos com aquela inical
            jLstPratosEncontrados.setBorder(javax.swing.BorderFactory.createLineBorder(
                    new java.awt.Color(153, 153, 153)));//Torna a lista visivel
            jLstPratosEncontrados.setBackground(new Color(102, 102, 255));//Torna a lista visivel
            for (Prato nome : nomes)//Adiciona o nome dos pratos a jList
            {
                listaModelo.addElement(nome.getNome());
            }
            if (nomes.isEmpty())//Verifca se a lista de nomes retornol algo
            {
                jBtnAdicionar.setEnabled(false);//Se nao encontrou nada desabilita o botao add
                if (!jTxtBuscaPratos.getText().contains("doctor"))
                {
                    listaModelo.addElement("'" + jTxtBuscaPratos.getText().toUpperCase() + "' não encontrado");
                }else
                {
                    listaModelo.addElement("Você gostaria de uma jujuba?");//#savetheday
                }
            }
        }else
        {
            limparListPratosEncontrados();
        }
    }//GEN-LAST:event_jTxtBuscaPratosKeyReleased

    private void jLstPratosEncontradosValueChanged(javax.swing.event.ListSelectionEvent evt)//GEN-FIRST:event_jLstPratosEncontradosValueChanged
    {//GEN-HEADEREND:event_jLstPratosEncontradosValueChanged
        // TODO add your handling code here:
        /*
            Adiciona o elemento selecionado na lista a caixa de pesquisa
        */
        if (jLstPratosEncontrados.getSelectedIndex() >= 0)
        {
            jTxtBuscaPratos.setText((String) jLstPratosEncontrados.getSelectedValue());
        }
    }//GEN-LAST:event_jLstPratosEncontradosValueChanged

    private void jBtnGerarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnGerarActionPerformed
    {//GEN-HEADEREND:event_jBtnGerarActionPerformed
        // TODO add your handling code here:
        /*
            Gera um número aletório para ser a senha do pedido
        */
        double a = Math.random() * 10000000;
        double b = Math.floor(a);
        int c = (int) b;
        jLblSenha.setText(String.valueOf(c));
    }//GEN-LAST:event_jBtnGerarActionPerformed

    private void jBtnAdicionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAdicionarActionPerformed
    {//GEN-HEADEREND:event_jBtnAdicionarActionPerformed
        // TODO add your handling code here:
        if (jLstPratosEncontrados.getSelectedIndex() < 0)
        {
            jLstPratosEncontrados.setSelectedIndex(0);
        }
        cont++;//Incrementa o número de itens do pedido
        mod = (DefaultTableModel) jTblPratosAdd.getModel();
        mod.addRow(new Object[]
        {
            cont, jLstPratosEncontrados.getSelectedValue()
        });//Adiciona na TABELA o número do item e o nome do item
        pratos.add(nomes.get(jLstPratosEncontrados.getSelectedIndex()));/* Adiciona no List<Prato> o item*/
        preco += nomes.get(jLstPratosEncontrados.getSelectedIndex()).getPreco();//Atualiza o valor total
        jTxtTotal.setText(NumberFormat.getCurrencyInstance().format(preco));
        jTxtBuscaPratos.setText("");
        limparListPratosEncontrados();
    }//GEN-LAST:event_jBtnAdicionarActionPerformed

    private void jTxtIDFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtIDFocusLost
    {//GEN-HEADEREND:event_jTxtIDFocusLost
        // TODO add your handling code here:
        Pedido p = null;
        int id;
        if (!Diversos.testaNum(jTxtID.getText(), titulo))
        {
            jTxtID.setText("");
            jTxtID.requestFocus();
        } else
        {
            id = Integer.parseInt(jTxtID.getText());
            if (!Diversos.intervalo(id, 0, 0, titulo))
            {
                jTxtID.setText("");
                jTxtID.requestFocus();
            } else
            {
                p = dPE.busca(id, 0);
                if (p == null)
                {
                    jBtnIncluir.setEnabled(true);
                    jBtnTravar.setEnabled(true);
                    jBtnGerar.setEnabled(true);
                    Diversos.mostrarDados("Pedido inexistente", titulo, false);
                } else
                {
                    clearTable();//Limpa tabela
                    carregarObjeto(p);
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
                    jBtnTravar.setEnabled(false);
                    jBtnGerar.setEnabled(false);
                }
            }
            jTxtID.setEditable(false);
        }

    }//GEN-LAST:event_jTxtIDFocusLost

    private void jBtnEnderecoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnEnderecoActionPerformed
    {//GEN-HEADEREND:event_jBtnEnderecoActionPerformed
        // TODO add your handling code here:
        new Interface.AtendenteView.JDialogEndereco(this, true).setVisible(true);//Abre janela de endereço
    }//GEN-LAST:event_jBtnEnderecoActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        limpar();
        int posi = jCmbEntregadorNome.getSelectedIndex();
        try
        {
            lista = dE.carrega();
            jCmbEntregadorNome.removeAllItems();
            for (int ind = 0; ind < lista.size(); ind++)
            {
                Object o = lista.get(ind);
                Entregador en = (Entregador) o;
                jCmbEntregadorNome.addItem(en.getNome());
            }
            jCmbEntregadorNome.setSelectedIndex(-1);
            if (posi > -1)
            {
                jCmbEntregadorNome.setSelectedIndex(posi);
            }
        } catch (Exception e)
        {
            Diversos.mostrarDados("Problemas ao carregar, inexistência de entregadores"
                    + e.getMessage(), "19:39", false);
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jTxtBuscaPratosFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtBuscaPratosFocusLost
    {//GEN-HEADEREND:event_jTxtBuscaPratosFocusLost
        // TODO add your handling code here:
        /*
            Esconder o jList quando o quando a caixa de busca perder o foco
        */
        String novoComp = null;
        try
        {
            novoComp = evt.getOppositeComponent().getName();
        } catch (Exception e)
        {

        }
        if (novoComp == null)
        {
            novoComp = "0";
        }
        if (!(novoComp.equals("AddButton") || novoComp.equals("PratosList")))
        {
            jTxtBuscaPratos.setText("");
            limparListPratosEncontrados();
        }

    }//GEN-LAST:event_jTxtBuscaPratosFocusLost

    private void jLstPratosEncontradosFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jLstPratosEncontradosFocusLost
    {//GEN-HEADEREND:event_jLstPratosEncontradosFocusLost
        // TODO add your handling code here:
        /*
            Esconder o jList quando o mesmo perder o foco
        */
        String novoComp = null;
        try
        {
            novoComp = evt.getOppositeComponent().getName();
        } catch (Exception e)
        {

        }
        if (novoComp == null)
        {
            novoComp = "0";
        }
        if (!(novoComp.equals("AddButton") || novoComp.equals("PratosList") || novoComp.equals("NomeField")))
        {
            jTxtBuscaPratos.setText("");
            limparListPratosEncontrados();
        }
    }//GEN-LAST:event_jLstPratosEncontradosFocusLost

    /**
     * @param args the command line arguments
     */
    private Thread tempoDecorrido(final String inicio)
    {
        /* 
           Muda o valor do campo tempo decorrido de 1 em 1 s  
        */
        Thread t = new Thread()
        {
            public void run()
            {
                while (go2 == true)
                {
                    try
                    {
                        Thread.sleep(1000);
                    } catch (InterruptedException ex)
                    {
                        ex.printStackTrace();
                    }
                    jLblTempoDecorrido.setText(Diversos.tempoDecorrido(inicio));
                }
            }
        };
        return t;
    }

    private Thread relogio()
    {
        /*
            Relogio
        */
        Thread t = new Thread()
        {
            public void run()
            {
                while (go == true)
                {
                    Date hoje = new Date();
                    DateFormat dH = DateFormat.getDateTimeInstance();
                    jFtdTxtData.setText(dH.format(hoje));
                }
            }
        };
        return t;
    }

    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        JFrmPedido p = new JFrmPedido();
        p.setVisible(true);
        rel = p.relogio();
        rel.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JButton jBtnAdicionar;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnEndereco;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnGerar;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JButton jBtnTravar;
    private javax.swing.JComboBox jCmbEntregadorNome;
    private javax.swing.JComboBox jCmbFormaPagamento;
    private javax.swing.JLabel jFtdTxtData;
    private javax.swing.JFormattedTextField jFtdTxtTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblLimpar;
    private javax.swing.JLabel jLblSenha;
    private javax.swing.JLabel jLblStatus;
    private javax.swing.JLabel jLblTempoDecorrido;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JList jLstPratosEncontrados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JPanel jPnlInfo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTblPratosAdd;
    private javax.swing.JTextField jTxtBuscaPratos;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtNomeCliente;
    private javax.swing.JTextField jTxtTotal;
    // End of variables declaration//GEN-END:variables
}
