/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.GerenteView;

import Interface.GerenteView.JFrmEntregador;
import Negocio.Diversos;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.OutputStream;

/**
 *
 * @author aluno
 */
public class FileBox extends javax.swing.JFrame {

    /**
     * Creates new form FileBox
     */
    JFrmEntregador e;
    public FileBox(JFrmEntregador e) {
        initComponents();
        setLookAndFeel();
        this.e = e;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel2 = new javax.swing.JPanel();
        jFileChooserFoto = new javax.swing.JFileChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("August- Selecione uma imagem");

        jFileChooserFoto.setApproveButtonText("Carregar");
        jFileChooserFoto.setCurrentDirectory(new java.io.File("H:\\Pedro\\WEB\\Arquivos_htm\\doctor whosite"));
        jFileChooserFoto.setDialogTitle("Selecione uma imagem");
        jFileChooserFoto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jFileChooserFotoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooserFoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jFileChooserFoto, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooserFotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooserFotoActionPerformed
        // TODO add your handling code here:
        
        if(!evt.getActionCommand().equals("CancelSelection"))//Se não clicou no botão de cancelar
        {
            try
            {
                File arquivo = jFileChooserFoto.getSelectedFile();//Guarda o arquivo selecionado
                System.out.println(arquivo.getAbsolutePath());
                InputStream in = new FileInputStream(arquivo.getAbsolutePath());/*Cria uma entrada no caminho do 
                                                                                aruivo selecionado*/
                OutputStream out = new FileOutputStream(Diversos.diretorio+arquivo.getName());/*Cria uma saída no
                                                                                     diretorio especificado*/
                byte[] buffer = new byte[1024];
                int lenght;
                while((lenght = in.read(buffer)) > 0)//Escreve os bytes da entrada na saída
                {
                    out.write(buffer, 0, lenght);
                }
                in.close();
                out.close();
                e.changeFoto(Diversos.diretorio+arquivo.getName());//Diz a tela que chamou esta, para mudar a foto 
                dispose();
            }catch(IOException e)
            {
                Diversos.mostrarDados("Veja se o diretório esta correto!\n"
                        + "Direotrio atual: "+Diversos.diretorio+"\nError: "+e.getMessage(),
                        "Error:", false);
                //e.printStackTrace();
            }
        }
        else
        {
            dispose();
        }
    }//GEN-LAST:event_jFileChooserFotoActionPerformed
    public void setLookAndFeel()
    {
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrmEntregador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
    }
    
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooserFoto;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
