/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.GerenteView;

/**
 *
 * @author Pedro
 */
import Negocio.*;
import Persistencia.DaoIngrediente;
import Persistencia.DaoLote;
import java.awt.Color;
import java.awt.Component;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JLabel;
public class JFrmLote extends javax.swing.JFrame
{

    /**
     * Creates new form Lote
     */

    public JFrmLote(JFrame i, Lote l)
    {
        initComponents();
        this.l = l;
        this.i = (JFrmIngrediente)i;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTxtQuantidadeAtual = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTxtQuantidadeIncial = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jFtdTxtValidade = new javax.swing.JFormattedTextField();
        jLblUni = new javax.swing.JLabel();
        jLblUni2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jTxtNumeroLote = new javax.swing.JTextField();
        jLblTitulo = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jCmbNomeProduto = new javax.swing.JComboBox();
        jTxtIDProduto = new javax.swing.JTextField();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jBtnExcluir = new javax.swing.JButton();
        jLblVoltar = new javax.swing.JLabel();
        jLblLimpar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lote");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowActivated(java.awt.event.WindowEvent evt)
            {
                formWindowActivated(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(22, 73, 154));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED, new java.awt.Color(255, 255, 0), new java.awt.Color(255, 153, 51)));

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Produto:");

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Quantidade Atual:");

        jTxtQuantidadeAtual.setBackground(new java.awt.Color(102, 102, 255));
        jTxtQuantidadeAtual.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtQuantidadeAtual.setForeground(new java.awt.Color(255, 255, 255));
        jTxtQuantidadeAtual.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtQuantidadeAtual.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTxtQuantidadeAtualKeyReleased(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Quantidade Inicial:");

        jTxtQuantidadeIncial.setEditable(false);
        jTxtQuantidadeIncial.setBackground(new java.awt.Color(102, 102, 255));
        jTxtQuantidadeIncial.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtQuantidadeIncial.setForeground(new java.awt.Color(255, 255, 255));
        jTxtQuantidadeIncial.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        jLabel7.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Validade:");

        jFtdTxtValidade.setBackground(new java.awt.Color(102, 102, 255));
        jFtdTxtValidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jFtdTxtValidade.setForeground(new java.awt.Color(255, 255, 255));
        jFtdTxtValidade.setFormatterFactory(Diversos.FormatoMascara(1));
        jFtdTxtValidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jLblUni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblUni.setForeground(new java.awt.Color(255, 255, 255));

        jLblUni2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblUni2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Lote Nº:");

        jTxtNumeroLote.setBackground(new java.awt.Color(102, 102, 255));
        jTxtNumeroLote.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtNumeroLote.setForeground(new java.awt.Color(255, 255, 255));
        jTxtNumeroLote.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtNumeroLote.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtNumeroLoteFocusLost(evt);
            }
        });

        jLblTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setText("Lote");

        jPanel6.setBackground(new java.awt.Color(22, 75, 154));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cr2.png"))); // NOI18N

        jLabel15.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("August");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jLabel15)
                .addGap(2, 2, 2)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jCmbNomeProduto.setBackground(new java.awt.Color(102, 102, 255));
        jCmbNomeProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCmbNomeProduto.setForeground(new java.awt.Color(255, 255, 255));
        jCmbNomeProduto.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbNomeProdutoActionPerformed(evt);
            }
        });

        jTxtIDProduto.setEditable(false);
        jTxtIDProduto.setBackground(new java.awt.Color(102, 102, 255));
        jTxtIDProduto.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtIDProduto.setForeground(new java.awt.Color(255, 255, 255));
        jTxtIDProduto.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));

        jPnlBotoes.setBackground(new java.awt.Color(22, 73, 154));

        jBtnIncluir.setBackground(new java.awt.Color(102, 102, 255));
        jBtnIncluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnIncluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.setBorderPainted(false);
        jBtnIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setBackground(new java.awt.Color(102, 102, 255));
        jBtnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setBorderPainted(false);
        jBtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jBtnExcluir.setBackground(new java.awt.Color(102, 102, 255));
        jBtnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setBorderPainted(false);
        jBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLblVoltar.setBackground(new java.awt.Color(204, 0, 0));
        jLblVoltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jLblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVoltar.setText("←");
        jLblVoltar.setToolTipText("Voltar");
        jLblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblVoltarMouseClicked(evt);
            }
        });

        jLblLimpar.setBackground(new java.awt.Color(204, 0, 0));
        jLblLimpar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jLblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/limpar2.png"))); // NOI18N
        jLblLimpar.setToolTipText("Limpar");
        jLblLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblLimpar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addComponent(jLblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jBtnIncluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnExcluir)
                .addGap(14, 14, 14)
                .addComponent(jLblLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblLimpar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFtdTxtValidade))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addGap(12, 12, 12)
                                .addComponent(jTxtQuantidadeIncial, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(4, 4, 4)
                        .addComponent(jLblUni2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jTxtQuantidadeAtual))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jCmbNomeProduto, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(12, 12, 12)
                                    .addComponent(jTxtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addComponent(jLblUni, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jPnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLblTitulo)
                        .addGap(4, 4, 4)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel14)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jTxtNumeroLote, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCmbNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTxtIDProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTxtQuantidadeAtual, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLblUni, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jTxtQuantidadeIncial, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLblUni2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jFtdTxtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Persistencia
        DaoIngrediente dI = new DaoIngrediente();
        DaoLote dL = new DaoLote();
    //Negocio
        List<Object> lista = new ArrayList<>();
        Lote oldLote = null;/*
                            Caso alguem burro queira alterar a quantidade atual do lote
                            por aqui... salva a quantidade antiga para fazer uma subtração
                            deixar o Estoque Atual atualizado
                            */
    //Interface
      
    //Variaveis de Controle
        final String titulo = "August";
        boolean novo = true;// <-- Complexo demais pra se explicar
        Lote l = null;/* 
                        Basicamente me diz se essa janela foi chama por uma janela
                        do tipo ingrediente ou se ela foi aberta sozinha.
                       */
        JFrmIngrediente i;//Avisar a janela que chamou esta que houve mudança uma nos lotes...
    public void limpar()
    {
        jTxtNumeroLote.setText("");
        jTxtNumeroLote.setEditable(true);
        jCmbNomeProduto.removeAllItems();
        jCmbNomeProduto.setSelectedIndex(-1);
        jTxtQuantidadeAtual.setText("");
        jTxtQuantidadeIncial.setText("");
        jTxtQuantidadeIncial.setEditable(true);
        jLblUni.setText("");
        jLblUni2.setText("");
        jFtdTxtValidade.setText("");
        jBtnIncluir.setEnabled(false);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jTxtIDProduto.setText("");
        jTxtNumeroLote.requestFocusInWindow();
        lista.clear();
        oldLote = null;
    }
    public void carregarObjeto(Lote l)
    {
        
        jTxtNumeroLote.setText(String.valueOf(l.getNumero()));
        jCmbNomeProduto.removeAllItems();
        jCmbNomeProduto.addItem(l.getIngrediente().getNome());
        jCmbNomeProduto.setSelectedIndex(0);
        jTxtQuantidadeAtual.setText(String.valueOf(l.getQuantidadeAtual()));
        jTxtQuantidadeIncial.setText(String.valueOf(l.getQuantidadeInicial()));
        jFtdTxtValidade.setText(Diversos.parseBrazil(l.getValidade()));
        jLblUni.setText(l.getIngrediente().getUnidadeMedida());
        jLblUni2.setText(l.getIngrediente().getUnidadeMedida());
        jTxtIDProduto.setText(String.valueOf(l.getIngrediente().getID()));
        oldLote = l;
    }
    private void jTxtNumeroLoteFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtNumeroLoteFocusLost
    {//GEN-HEADEREND:event_jTxtNumeroLoteFocusLost
        Lote l = null;
        int numero;
        boolean sucesso = true;//Obteu sucesso em carregar os produtos
        if(!Diversos.testaNum(jTxtNumeroLote.getText(), titulo))
        {
           jTxtNumeroLote.setText("");
           jTxtNumeroLote.requestFocusInWindow();
        }
        else
        { 
            numero = Integer.parseInt(jTxtNumeroLote.getText());
            if(!Diversos.intervalo(numero, 0, 0, titulo))
            {
                jTxtNumeroLote.setText("");
                jTxtNumeroLote.requestFocusInWindow();
            }
            else
            {
                l = dL.busca(numero, 0);
                if (l == null)
                {
                    novo = true;
                    jBtnIncluir.setEnabled(true);
                    Diversos.mostrarDados("Lote inexistente",titulo,false);
                    jTxtQuantidadeIncial.setEditable(false);
                    sucesso = carregarProdutos();
                }    
                else
                {  
                    novo = false;
                    carregarObjeto(l);
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
                    jTxtQuantidadeIncial.setEditable(true);
                }
                if(sucesso)
                {
                    jTxtNumeroLote.setEditable(false);
                }
            } 
        }
    }//GEN-LAST:event_jTxtNumeroLoteFocusLost

    private void formWindowActivated(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowActivated
    {//GEN-HEADEREND:event_formWindowActivated

    }//GEN-LAST:event_formWindowActivated

    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnIncluirActionPerformed
    {//GEN-HEADEREND:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Lote l;
        Ingrediente i = null;
        int id;
        if(
            !jTxtNumeroLote.getText().isEmpty()
            && jCmbNomeProduto.getSelectedIndex() > -1
            && !jTxtQuantidadeAtual.getText().isEmpty()
            && !jTxtQuantidadeIncial.getText().isEmpty()
            && !jFtdTxtValidade.getText().isEmpty()
        )
        {
            l = new Lote();
            id = Integer.parseInt((String)jTxtIDProduto.getText());
            l.setNumero(Integer.parseInt(jTxtNumeroLote.getText()));
            l.setQuantidadeAtual(Float.parseFloat(jTxtQuantidadeAtual.getText()));
            l.setQuantidadeInicial(Float.parseFloat(jTxtQuantidadeIncial.getText()));
            l.setValidade(Diversos.parseIngles(jFtdTxtValidade.getText()));
            Object o = dI.busca(id, 0);
            i = (Ingrediente) o;
            l.setIngrediente(i);
            if(jBtnIncluir.isEnabled())
            {
                if (dL.incluir(l))
                { //==true
                    Diversos.mostrarDados("Dados do lote foi inserido com sucesso", "I can see for miles", true);
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
                }
                else // ==false
                {
                    Diversos.mostrarDados("Problemas ao inserir os dados do lote)", titulo, false);
                }
            }
            else
            {
                if(dL.alterar(l))
                {
                    Diversos.mostrarDados("Dados do lote foram atualizados com sucesso", titulo, true);
                    if(oldLote.getQuantidadeAtual() >= l.getQuantidadeAtual())//Conta de subtração para Atualizar o Estoque Atual
                    {
                        dL.atualizarEstoque("out", oldLote.getQuantidadeAtual() - l.getQuantidadeAtual(), oldLote);
                    }
                    else
                    {
                        dL.atualizarEstoque("in", l.getQuantidadeAtual() - oldLote.getQuantidadeAtual(), l);
                    }
                }
                else
                {
                    Diversos.mostrarDados("Problemas ao atualizar os dados do lote", "Taxman!", false);
                    jBtnAlterar.setEnabled(false);
                    jBtnIncluir.setEnabled(false);
                }
            }
            jBtnIncluir.setEnabled(false);
        }
        else
        {
            Diversos.mostrarDados("Preencha todos os campos", "Doctor Robert", false);
        }
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAlterarActionPerformed
    {//GEN-HEADEREND:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        jBtnIncluirActionPerformed(evt);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnExcluirActionPerformed
    {//GEN-HEADEREND:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if (Diversos.confirmar("Deseja excluir?", "and your bird can sing"))
        {
            if(dL.excluir(Integer.parseInt(jTxtNumeroLote.getText()), 0))
            {
                Diversos.mostrarDados("Lote foi excluido com sucesso", titulo, true);
                limpar();
                jBtnAlterar.setEnabled(false);
                jBtnExcluir.setEnabled(false);
            }
            else
            {
                Diversos.mostrarDados("Problemas ao excluir um lote ","She said She said", false);
            }
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblVoltarMouseClicked
    {//GEN-HEADEREND:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        if(!(i == null))
        {
            i.atualizarDados(null);
        }
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jLblLimparMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblLimparMouseClicked
    {//GEN-HEADEREND:event_jLblLimparMouseClicked
        limpar();
    }//GEN-LAST:event_jLblLimparMouseClicked
    public boolean carregarProdutos()/*
                                        Essa função surgiu pq eu não estava pensando bem no momento...
                                        Enfim, ela sugiu pq eu não queria povoar o combo box assim que
                                        a janela fosse aberta...
                                    */
    {
        int posi = jCmbNomeProduto.getSelectedIndex();
        boolean ok = true;
            try
            {
               lista = dI.carrega();
               jCmbNomeProduto.removeAllItems();
               for(int ind=0; ind < lista.size(); ind++) 
               {
                   Object o = lista.get(ind);
                   Ingrediente i = (Ingrediente) o;
                   jCmbNomeProduto.addItem(i.getNome()); 
               }
               jCmbNomeProduto.setSelectedIndex(-1);
               jTxtIDProduto.setText("");
               jLblUni.setText("");
               jLblUni2.setText("");
               if (posi > -1) 
                 jCmbNomeProduto.setSelectedIndex(posi);
               if(lista.size() == 0)
               {
                  Diversos.mostrarDados("Cadastre produtos primeiro!", "ué", false);
                  ok = false;
                  limpar();
                }
            } 
            catch(Exception e)
            {
                ok = false;
                Diversos.mostrarDados("Problemas ao carregar a lista: DaoIngrediente.carrega()" +
                        e.getMessage(), titulo, false); 
                e.printStackTrace();
            }
        return ok;
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        limpar();
        if(l==null)
        {
            limpar();
        }
        else
        {
            jTxtNumeroLote.setEditable(false);
            jBtnAlterar.setEnabled(true);
            jBtnExcluir.setEnabled(true);
            novo = false;
            carregarObjeto(l);
        }
    }//GEN-LAST:event_formWindowOpened

    private void jCmbNomeProdutoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbNomeProdutoActionPerformed
    {//GEN-HEADEREND:event_jCmbNomeProdutoActionPerformed
        // TODO add your handling code here:
        if(novo)
        {
            int ind = jCmbNomeProduto.getSelectedIndex();
            if(ind > -1)
            {
                Object o = lista.get(ind);
                Ingrediente i = (Ingrediente) o;
                jTxtIDProduto.setText(String.valueOf(i.getID()));
                jLblUni.setText(i.getUnidadeMedida());
                jLblUni2.setText(i.getUnidadeMedida());
            }
        }
    }//GEN-LAST:event_jCmbNomeProdutoActionPerformed

    private void jTxtQuantidadeAtualKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtQuantidadeAtualKeyReleased
    {//GEN-HEADEREND:event_jTxtQuantidadeAtualKeyReleased
        // TODO add your handling code here:
        if(novo)//Caso o lote seja novo a quantidade atual é igual a inicial
        {
            jTxtQuantidadeIncial.setText(jTxtQuantidadeAtual.getText());
        }
    }//GEN-LAST:event_jTxtQuantidadeAtualKeyReleased
    public void mouseOff(Component comp)//Obsoleto explicação em JFrmIngrediente
    {
        JLabel bot = (JLabel) comp;
        bot.setBorder(null);
    }
    public void mouseIn(Component comp)
    {
        JLabel bot = (JLabel) comp;
        bot.setBorder(javax.swing.BorderFactory.createLineBorder(Color.white, 1));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrmLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrmLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrmLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrmLote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFrmLote(null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JComboBox jCmbNomeProduto;
    private javax.swing.JFormattedTextField jFtdTxtValidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLblLimpar;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLblUni;
    private javax.swing.JLabel jLblUni2;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTxtIDProduto;
    private javax.swing.JTextField jTxtNumeroLote;
    private javax.swing.JTextField jTxtQuantidadeAtual;
    private javax.swing.JTextField jTxtQuantidadeIncial;
    // End of variables declaration//GEN-END:variables
}
