/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.GerenteView;

/**
 *
 * @author Pedro
 */
import Interface.CustomizarTabela.CustomCelulaJTable;
import Negocio.Diversos;
import Negocio.Ingrediente;
import Negocio.Prato;
import Persistencia.DaoIngrediente;
import Persistencia.DaoPrato;
import java.awt.Color;
import java.text.NumberFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.table.DefaultTableModel;
public class JFrmPrato extends javax.swing.JFrame
{

    /**
     * Creates new form Refeição
     */
    public JFrmPrato()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        Logo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jPnlBotoes = new javax.swing.JPanel();
        jBtnIncluir = new javax.swing.JButton();
        jBtnAlterar = new javax.swing.JButton();
        jLblVoltar = new javax.swing.JLabel();
        jBtnExcluir = new javax.swing.JButton();
        jLblLimpar = new javax.swing.JLabel();
        jLblTitulo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTxtNome = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jCmBSessao = new javax.swing.JComboBox();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxtAreaModoPreparo = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        jTxtPreco = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel18 = new javax.swing.JLabel();
        jCmbNomeIngrediente = new javax.swing.JComboBox();
        jBtnAdd = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTblListaIngredientes = new javax.swing.JTable();
        jLabel20 = new javax.swing.JLabel();
        jTxtQuantidade = new javax.swing.JTextField();
        jLblUni = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pratos");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(22, 73, 154));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51), 2));
        jPanel1.setForeground(new java.awt.Color(255, 51, 51));

        Logo.setBackground(new java.awt.Color(22, 73, 154));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/cr2.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(0, 0, 0));
        jLabel25.setText("August");

        javax.swing.GroupLayout LogoLayout = new javax.swing.GroupLayout(Logo);
        Logo.setLayout(LogoLayout);
        LogoLayout.setHorizontalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LogoLayout.createSequentialGroup()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        LogoLayout.setVerticalGroup(
            LogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1)
            .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPnlBotoes.setBackground(new java.awt.Color(22, 73, 154));

        jBtnIncluir.setBackground(new java.awt.Color(102, 102, 255));
        jBtnIncluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnIncluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnIncluir.setText("Incluir");
        jBtnIncluir.setBorderPainted(false);
        jBtnIncluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnIncluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnIncluirActionPerformed(evt);
            }
        });

        jBtnAlterar.setBackground(new java.awt.Color(102, 102, 255));
        jBtnAlterar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnAlterar.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAlterar.setText("Alterar");
        jBtnAlterar.setBorderPainted(false);
        jBtnAlterar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAlterar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAlterarActionPerformed(evt);
            }
        });

        jLblVoltar.setBackground(new java.awt.Color(204, 0, 0));
        jLblVoltar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblVoltar.setForeground(new java.awt.Color(255, 255, 255));
        jLblVoltar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblVoltar.setText("←");
        jLblVoltar.setToolTipText("Voltar");
        jLblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblVoltar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblVoltarMouseClicked(evt);
            }
        });

        jBtnExcluir.setBackground(new java.awt.Color(102, 102, 255));
        jBtnExcluir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnExcluir.setForeground(new java.awt.Color(255, 255, 255));
        jBtnExcluir.setText("Excluir");
        jBtnExcluir.setBorderPainted(false);
        jBtnExcluir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnExcluir.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnExcluirActionPerformed(evt);
            }
        });

        jLblLimpar.setBackground(new java.awt.Color(204, 0, 0));
        jLblLimpar.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLblLimpar.setForeground(new java.awt.Color(255, 255, 255));
        jLblLimpar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMG/limpar2.png"))); // NOI18N
        jLblLimpar.setToolTipText("Limpar");
        jLblLimpar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLblLimpar.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                jLblLimparMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPnlBotoesLayout = new javax.swing.GroupLayout(jPnlBotoes);
        jPnlBotoes.setLayout(jPnlBotoesLayout);
        jPnlBotoesLayout.setHorizontalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPnlBotoesLayout.createSequentialGroup()
                .addComponent(jLblVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLblLimpar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPnlBotoesLayout.setVerticalGroup(
            jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnIncluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPnlBotoesLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPnlBotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblVoltar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblLimpar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        jLblTitulo.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLblTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLblTitulo.setText("Prato");

        jLabel14.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("ID:");

        jTxtID.setBackground(new java.awt.Color(102, 102, 255));
        jTxtID.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtID.setForeground(new java.awt.Color(255, 255, 255));
        jTxtID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtID.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtIDFocusLost(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Nome:");

        jTxtNome.setBackground(new java.awt.Color(102, 102, 255));
        jTxtNome.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtNome.setForeground(new java.awt.Color(255, 255, 255));
        jTxtNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtNome.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtNomeFocusLost(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Sessão:");

        jCmBSessao.setBackground(new java.awt.Color(102, 102, 255));
        jCmBSessao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCmBSessao.setForeground(new java.awt.Color(255, 255, 255));
        jCmBSessao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sobremesa", "Entrada", "Massa", "Carne" }));
        jCmBSessao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmBSessaoActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Modo de Preparo:");

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jTxtAreaModoPreparo.setBackground(new java.awt.Color(102, 102, 255));
        jTxtAreaModoPreparo.setColumns(20);
        jTxtAreaModoPreparo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtAreaModoPreparo.setForeground(new java.awt.Color(255, 255, 255));
        jTxtAreaModoPreparo.setLineWrap(true);
        jTxtAreaModoPreparo.setRows(5);
        jTxtAreaModoPreparo.setWrapStyleWord(true);
        jTxtAreaModoPreparo.setBorder(null);
        jScrollPane1.setViewportView(jTxtAreaModoPreparo);

        jLabel19.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Preço:");

        jTxtPreco.setBackground(new java.awt.Color(102, 102, 255));
        jTxtPreco.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTxtPreco.setForeground(new java.awt.Color(255, 255, 255));
        jTxtPreco.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255), 2));
        jTxtPreco.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTxtPrecoKeyReleased(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(105, 105, 255)), "Ingredientes", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Light", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel18.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setText("Nome:");

        jCmbNomeIngrediente.setBackground(new java.awt.Color(102, 102, 255));
        jCmbNomeIngrediente.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCmbNomeIngrediente.setForeground(new java.awt.Color(255, 255, 255));
        jCmbNomeIngrediente.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbNomeIngredienteActionPerformed(evt);
            }
        });

        jBtnAdd.setBackground(new java.awt.Color(102, 102, 255));
        jBtnAdd.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnAdd.setForeground(new java.awt.Color(255, 255, 255));
        jBtnAdd.setText("Add");
        jBtnAdd.setToolTipText("Adicionar a lista");
        jBtnAdd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jBtnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnAdd.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnAddActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(102, 102, 255));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 255)));

        jTblListaIngredientes.setBackground(new java.awt.Color(153, 153, 255));
        jTblListaIngredientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "Nº", "Quantidade", "Ingrediente"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTblListaIngredientes.setGridColor(new java.awt.Color(234, 234, 234));
        jTblListaIngredientes.setRowHeight(25);
        jTblListaIngredientes.setShowHorizontalLines(false);
        jTblListaIngredientes.setShowVerticalLines(false);
        jScrollPane2.setViewportView(jTblListaIngredientes);
        if (jTblListaIngredientes.getColumnModel().getColumnCount() > 0)
        {
            jTblListaIngredientes.getColumnModel().getColumn(0).setResizable(false);
            jTblListaIngredientes.getColumnModel().getColumn(0).setCellRenderer(tdRenderer);
            jTblListaIngredientes.getColumnModel().getColumn(1).setResizable(false);
            jTblListaIngredientes.getColumnModel().getColumn(1).setCellRenderer(tdRenderer);
            jTblListaIngredientes.getColumnModel().getColumn(2).setResizable(false);
            jTblListaIngredientes.getColumnModel().getColumn(2).setCellRenderer(tdRenderer);
        }
        if (jTblListaIngredientes.getColumnModel().getColumnCount() > 0)
        {
            jTblListaIngredientes.getColumnModel().getColumn(0).setHeaderRenderer(new Interface.CustomizarTabela.CustomCabecalhoJTable(1));
            jTblListaIngredientes.getColumnModel().getColumn(1).setHeaderRenderer(new Interface.CustomizarTabela.CustomCabecalhoJTable(1));
            jTblListaIngredientes.getColumnModel().getColumn(2).setHeaderRenderer(new Interface.CustomizarTabela.CustomCabecalhoJTable(1));
        }

        jScrollPane2.getViewport().setBackground(new Color(102,102,255));

        jLabel20.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Quantidade:");

        jTxtQuantidade.setBackground(new java.awt.Color(102, 102, 255));
        jTxtQuantidade.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTxtQuantidade.setForeground(new java.awt.Color(255, 255, 255));
        jTxtQuantidade.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtQuantidade.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jTxtQuantidade.addFocusListener(new java.awt.event.FocusAdapter()
        {
            public void focusLost(java.awt.event.FocusEvent evt)
            {
                jTxtQuantidadeFocusLost(evt);
            }
        });
        jTxtQuantidade.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                jTxtQuantidadeKeyReleased(evt);
            }
        });

        jLblUni.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblUni.setForeground(new java.awt.Color(255, 255, 255));
        jLblUni.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblUni.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jCmbNomeIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel20)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtQuantidade)
                        .addGap(4, 4, 4)
                        .addComponent(jLblUni, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 517, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jCmbNomeIngrediente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblUni, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLblTitulo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtNome)
                            .addComponent(jTxtID)
                            .addComponent(jCmBSessao, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 273, Short.MAX_VALUE)
                            .addComponent(jTxtPreco))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jPnlBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Logo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTxtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jCmBSessao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jTxtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jScrollPane1)))
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPnlBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    //Persistencia
        DaoIngrediente dI = new DaoIngrediente();
        DaoPrato dP = new DaoPrato();
    //Negocio
        List<Object> lista = new ArrayList<>();
        List<Ingrediente> ingredientes = new ArrayList<>();
        List<Float> quantidades= new ArrayList<>();/*Guarda quantidade de cada ingrediente.
                                                     Ambos usam o mesmo indice*/
    //Interface  
        CustomCelulaJTable tdRenderer = new CustomCelulaJTable(1);
        DefaultTableModel mod;
    //Variaveis de Controle
        int cont = 0;//O 'N' da tabela
        final String titulo = "August";
        
    public void limpar()
    {
        jTxtID.setText("");
        jTxtID.setEditable(true);
        jTxtNome.setText("");
        jCmBSessao.setSelectedIndex(-1);
        jTxtPreco.setText("");
        jTxtAreaModoPreparo.setText("");
        jCmbNomeIngrediente.setSelectedIndex(-1);
        jBtnIncluir.setEnabled(false);
        jBtnAlterar.setEnabled(false);
        jBtnExcluir.setEnabled(false);
        jTxtNome.setText("");
        jTxtID.requestFocusInWindow();
        clearTable();
        ingredientes.clear();
        quantidades.clear();
        jLblUni.setText("");
        jTxtQuantidade.setText("");
        cont = 0;
    }
    public void clearTable()
    {
        mod =(DefaultTableModel)jTblListaIngredientes.getModel();
        for(int i = mod.getRowCount(); i > 0; i--)
        {
            mod.removeRow(i-1);
        }
    }
    public void carregarObjeto(Prato p)
    {
        clearTable();
        jTxtID.setText(String.valueOf(p.getID()));
        jTxtNome.setText(p.getNome());
        jCmBSessao.setSelectedItem(p.getSecao());
        jTxtPreco.setText(NumberFormat.getCurrencyInstance().format(p.getPreco()));
        jTxtAreaModoPreparo.setText(p.getModoPreparo());
        mod = (DefaultTableModel)jTblListaIngredientes.getModel();
        for(int i = 0; i < p.getIngrediente().size(); i++)
        {
            mod.addRow(new Object[]{i+1, p.getQuantidade(i)+" "+p.getIngrediente(i).getUnidadeMedida(),
                      p.getIngrediente(i).getNome()});
        }
    }
    private void jBtnIncluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnIncluirActionPerformed
    {//GEN-HEADEREND:event_jBtnIncluirActionPerformed
        // TODO add your handling code here:
        Prato p;
        int id;
        if(!jTxtID.getText().isEmpty()
            && !jTxtNome.getText().isEmpty()
            && jCmBSessao.getSelectedIndex() > -1
            && !jTxtPreco.getText().isEmpty()
            && !jTxtAreaModoPreparo.getText().isEmpty()
            && jTblListaIngredientes.getRowCount() > 0
        )
        {
            p = new Prato();
            p.setID(Integer.parseInt(jTxtID.getText()));
            p.setNome(jTxtNome.getText());
            p.setSecao(jCmBSessao.getSelectedItem().toString());
            String preco = jTxtPreco.getText().replace(",", ".");
            preco = preco.replace("R$ ", "");
            p.setPreco(Float.parseFloat(preco));
            p.setModoPreparo(jTxtAreaModoPreparo.getText());
            p.setIngrediente(ingredientes);
            p.setQuantidade(quantidades);
            if(jBtnIncluir.isEnabled())
            {
                if (dP.incluir(p))
                { //==true
                    Diversos.mostrarDados("Prato foi inserido com sucesso", "'-'", true);
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
                }
                else // ==false
                {
                    Diversos.mostrarDados("Problemas ao inserir os dados do prato)", titulo, false);
                }
            }
            else
            {
                if(dP.alterar(p))
                {
                    Diversos.mostrarDados("Dados do prato foram atualizados com sucesso", titulo, true);
                }
                else
                {
                    Diversos.mostrarDados("Problemas ao atualizar os dados do prato", "Its a new World", false);
                    jBtnAlterar.setEnabled(false);
                    jBtnIncluir.setEnabled(false);
                }
            }
            jBtnIncluir.setEnabled(false);
        }
        else
        {
            Diversos.mostrarDados("Preencha todos os campos", "42!", false);
        }
    }//GEN-LAST:event_jBtnIncluirActionPerformed

    private void jBtnAlterarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAlterarActionPerformed
    {//GEN-HEADEREND:event_jBtnAlterarActionPerformed
        // TODO add your handling code here:
        jBtnIncluirActionPerformed(evt);
    }//GEN-LAST:event_jBtnAlterarActionPerformed

    private void jLblVoltarMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblVoltarMouseClicked
    {//GEN-HEADEREND:event_jLblVoltarMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLblVoltarMouseClicked

    private void jBtnExcluirActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnExcluirActionPerformed
    {//GEN-HEADEREND:event_jBtnExcluirActionPerformed
        // TODO add your handling code here:
        if(Diversos.confirmar("Deseja excluir?", "knock knock"))
        {
            int existem = dP.verificaChave(Integer.parseInt(jTxtID.getText()));
            if (existem > 0)
            {
                if(Diversos.confirmar("Esse prato esta presente em: "
                    + ""+existem+" pedidos.\nDeseja realmente excluir?", titulo))
                if(dP.excluir(Integer.parseInt(jTxtID.getText()), 0))
                {
                    Diversos.mostrarDados("Prato foi excluido com sucesso", titulo, true);
                    limpar();
                    jBtnAlterar.setEnabled(false);
                    jBtnExcluir.setEnabled(false);
                } 
                else
                {
                    Diversos.mostrarDados("Problemas ao excluir um Prato ", "She said She said", false);
                }
            } 
            else
            {
                if(dP.excluir(Integer.parseInt(jTxtID.getText()), 0))
                {
                    Diversos.mostrarDados("Prato foi excluido com sucesso", titulo, true);
                    limpar();
                    jBtnAlterar.setEnabled(false);
                    jBtnExcluir.setEnabled(false);
                } 
                else
                {
                    Diversos.mostrarDados("Problemas ao excluir um Prato ", "She said She said", false);
                }
            }
        }
    }//GEN-LAST:event_jBtnExcluirActionPerformed

    private void jTxtIDFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtIDFocusLost
    {//GEN-HEADEREND:event_jTxtIDFocusLost
        // TODO add your handling code here:
        Prato p = null;
        int id;
        if(!Diversos.testaNum(jTxtID.getText(), titulo))
        {
            jTxtID.setText("");
            jTxtID.requestFocusInWindow();
        }
        else
        {
            id = Integer.parseInt(jTxtID.getText());
            if(!Diversos.intervalo(id, 0, 0, titulo))
            {
                jTxtID.setText("");
                jTxtID.requestFocusInWindow();
            }
            else
            {
                p = dP.busca(id, 0);
                if (p == null)
                {
                    jBtnIncluir.setEnabled(true);
                    jBtnAdd.setEnabled(true);
                    Diversos.mostrarDados("Ingrediente inexistente", titulo, false);
                }
                else
                {
                    carregarObjeto(p);
                    jBtnAdd.setEnabled(false);
                    jBtnAlterar.setEnabled(true);
                    jBtnExcluir.setEnabled(true);
                }
            }
            jTxtID.setEditable(false);
        }
    }//GEN-LAST:event_jTxtIDFocusLost

    private void jTxtNomeFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtNomeFocusLost
    {//GEN-HEADEREND:event_jTxtNomeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtNomeFocusLost

    private void jBtnAddActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnAddActionPerformed
    {//GEN-HEADEREND:event_jBtnAddActionPerformed
        // TODO add your handling code here:
        if(!jTxtQuantidade.getText().isEmpty())//Testa e adiciona uma linha a tabela
        {
            cont++;
            mod =(DefaultTableModel)jTblListaIngredientes.getModel();
            mod.addRow(new Object[]{cont, jTxtQuantidade.getText(), jCmbNomeIngrediente.getSelectedItem()});
            ingredientes.add((Ingrediente)lista.get(jCmbNomeIngrediente.getSelectedIndex()));
            quantidades.add(Float.parseFloat(jTxtQuantidade.getText()));
        }
    }//GEN-LAST:event_jBtnAddActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        limpar();
        int posi = jCmbNomeIngrediente.getSelectedIndex();
        try
        {
           lista = dI.carrega();
           jCmbNomeIngrediente.removeAllItems();
           for(int ind=0; ind < lista.size(); ind++) 
           {
               Object o = lista.get(ind);
               Ingrediente i = (Ingrediente) o;
               jCmbNomeIngrediente.addItem(i.getNome()); 
           }
           jCmbNomeIngrediente.setSelectedIndex(-1);
           if (posi > -1) 
             jCmbNomeIngrediente.setSelectedIndex(posi);
        } 
        catch(Exception e)
        {
            Diversos.mostrarDados("Problemas ao carregar, inexistência de ingredientes" +
                    e.getMessage(), "Another Roman Leader", false); 
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jLblLimparMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLblLimparMouseClicked
    {//GEN-HEADEREND:event_jLblLimparMouseClicked
        // TODO add your handling code here:
        limpar();
    }//GEN-LAST:event_jLblLimparMouseClicked

    private void jTxtQuantidadeFocusLost(java.awt.event.FocusEvent evt)//GEN-FIRST:event_jTxtQuantidadeFocusLost
    {//GEN-HEADEREND:event_jTxtQuantidadeFocusLost
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtQuantidadeFocusLost

    private void jCmbNomeIngredienteActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbNomeIngredienteActionPerformed
    {//GEN-HEADEREND:event_jCmbNomeIngredienteActionPerformed
        //Troca a unidade de media conforme o ingrediente
        int posi = jCmbNomeIngrediente.getSelectedIndex();
        if(!lista.isEmpty())
        {
            if(posi < 0)
            {
                posi = 0;
            }
            Object o = lista.get(posi);
            Ingrediente i = (Ingrediente) o;
            jLblUni.setText(i.getUnidadeMedida());
        }
    }//GEN-LAST:event_jCmbNomeIngredienteActionPerformed

    private void jTxtQuantidadeKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtQuantidadeKeyReleased
    {//GEN-HEADEREND:event_jTxtQuantidadeKeyReleased
        // TODO add your handling code here:
        jTxtQuantidade.setText(Diversos.testaNum(jTxtQuantidade.getText(), 1));
    }//GEN-LAST:event_jTxtQuantidadeKeyReleased

    private void jTxtPrecoKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_jTxtPrecoKeyReleased
    {//GEN-HEADEREND:event_jTxtPrecoKeyReleased
        // TODO add your handling code here:
        
        jTxtPreco.setText(Diversos.testaNum(jTxtPreco.getText(), 1));
    }//GEN-LAST:event_jTxtPrecoKeyReleased

    private void jCmBSessaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmBSessaoActionPerformed
    {//GEN-HEADEREND:event_jCmBSessaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCmBSessaoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrmPrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFrmPrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Logo;
    private javax.swing.JButton jBtnAdd;
    private javax.swing.JButton jBtnAlterar;
    private javax.swing.JButton jBtnExcluir;
    private javax.swing.JButton jBtnIncluir;
    private javax.swing.JComboBox jCmBSessao;
    private javax.swing.JComboBox jCmbNomeIngrediente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLblLimpar;
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JLabel jLblUni;
    private javax.swing.JLabel jLblVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPnlBotoes;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTblListaIngredientes;
    private javax.swing.JTextArea jTxtAreaModoPreparo;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JTextField jTxtNome;
    private javax.swing.JTextField jTxtPreco;
    private javax.swing.JTextField jTxtQuantidade;
    // End of variables declaration//GEN-END:variables
}
