/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Interface.EntregadorView;
import Negocio.Diversos;
import Negocio.Entregador;
import Negocio.Pedido;
import Persistencia.DaoEntregador;
import Persistencia.DaoPedido;
import java.awt.Color;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JLabel;

/**
 *
 * @author Pedro
 */
public class JFrmEntregadorPedido extends javax.swing.JFrame
{

    /**
     * Creates new form EntregadorPedido
     */
    public JFrmEntregadorPedido()
    {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        btgTema = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jLblCliente = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLblMunicipio = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLblBairro = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLblRua = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLblNumero = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jCmbNumeroPedido = new javax.swing.JComboBox();
        jLblEntregador = new javax.swing.JLabel();
        jBtnConfirmacao = new javax.swing.JButton();
        jMBEntrega = new javax.swing.JMenuBar();
        jMnSair = new javax.swing.JMenu();
        jMnISair = new javax.swing.JMenuItem();
        jMnTema = new javax.swing.JMenu();
        jChkMnILightGray = new javax.swing.JCheckBoxMenuItem();
        jChkMnIBlueMint = new javax.swing.JCheckBoxMenuItem();
        jMnEntregador = new javax.swing.JMenu();
        jMnISelecionar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("August- Entrega");
        setUndecorated(true);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("Entregador");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("Pedido");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("Nome Cliente:");

        jLblCliente.setBackground(new java.awt.Color(153, 153, 255));
        jLblCliente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblCliente.setForeground(new java.awt.Color(255, 255, 255));
        jLblCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblCliente.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Municipio:");

        jLblMunicipio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblMunicipio.setForeground(new java.awt.Color(255, 255, 255));
        jLblMunicipio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblMunicipio.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(204, 204, 204));
        jLabel8.setText("Bairro:");

        jLblBairro.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblBairro.setForeground(new java.awt.Color(255, 255, 255));
        jLblBairro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblBairro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setText("Rua:");

        jLblRua.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblRua.setForeground(new java.awt.Color(255, 255, 255));
        jLblRua.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblRua.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("Nº:");

        jLblNumero.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblNumero.setForeground(new java.awt.Color(255, 255, 255));
        jLblNumero.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblNumero.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(204, 204, 204));
        jLabel14.setText("Pedido Nº:");

        jCmbNumeroPedido.setBackground(new java.awt.Color(204, 204, 204));
        jCmbNumeroPedido.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jCmbNumeroPedido.setForeground(new java.awt.Color(255, 255, 255));
        jCmbNumeroPedido.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCmbNumeroPedidoActionPerformed(evt);
            }
        });

        jLblEntregador.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLblEntregador.setForeground(new java.awt.Color(255, 255, 255));
        jLblEntregador.setText("-");
        jLblEntregador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jBtnConfirmacao.setBackground(new java.awt.Color(102, 102, 102));
        jBtnConfirmacao.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jBtnConfirmacao.setForeground(new java.awt.Color(255, 255, 255));
        jBtnConfirmacao.setText("Efetuar Confirmação");
        jBtnConfirmacao.setBorderPainted(false);
        jBtnConfirmacao.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jBtnConfirmacao.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jBtnConfirmacaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLblEntregador, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel14)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jBtnConfirmacao, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                                .addComponent(jCmbNumeroPedido, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                            .addComponent(jLblBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblRua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblNumero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel4)
                                    .addComponent(jLblCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel6)
                                    .addComponent(jLblMunicipio, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                    .addComponent(jLblBairro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                                    .addComponent(jLblRua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLblNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLblEntregador)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCmbNumeroPedido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtnConfirmacao)))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jMBEntrega.setBackground(new java.awt.Color(255, 255, 255));
        jMBEntrega.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));

        jMnSair.setBackground(new java.awt.Color(102, 102, 255));
        jMnSair.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jMnSair.setText("Sair");
        jMnSair.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnISair.setText("Sair");
        jMnISair.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMnISairActionPerformed(evt);
            }
        });
        jMnSair.add(jMnISair);

        jMBEntrega.add(jMnSair);

        jMnTema.setBackground(new java.awt.Color(102, 102, 255));
        jMnTema.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jMnTema.setText("Tema");
        jMnTema.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btgTema.add(jChkMnILightGray);
        jChkMnILightGray.setSelected(true);
        jChkMnILightGray.setText("Light Gray");
        jChkMnILightGray.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jChkMnILightGrayPropertyChange(evt);
            }
        });
        jMnTema.add(jChkMnILightGray);

        btgTema.add(jChkMnIBlueMint);
        jChkMnIBlueMint.setText("Blue Mint");
        jChkMnIBlueMint.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jChkMnIBlueMintActionPerformed(evt);
            }
        });
        jMnTema.add(jChkMnIBlueMint);

        jMBEntrega.add(jMnTema);

        jMnEntregador.setBackground(new java.awt.Color(102, 102, 255));
        jMnEntregador.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 2));
        jMnEntregador.setText("Entregador");
        jMnEntregador.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMnISelecionar.setText("Selecionar");
        jMnISelecionar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMnISelecionarActionPerformed(evt);
            }
        });
        jMnEntregador.add(jMnISelecionar);

        jMBEntrega.add(jMnEntregador);

        setJMenuBar(jMBEntrega);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Persistencia 
        DaoEntregador dE = new DaoEntregador();
        DaoPedido dP = new DaoPedido();
    //Negocio
        List<Object> listaPed = new ArrayList<>();
        List<Object> listaEnt = new ArrayList<>();
    //Interface
        
    //Variaveis de Controle
        String entNome[];//Guarda o nome dos entregadores
        public static int entregadorAtual = 0;
    
    public void carregarCombo(int entregador)//Carrega o comboBox
    {
        int posi = jCmbNumeroPedido.getSelectedIndex();
        try
        {
            listaPed = dP.carrega(entregador);
            jCmbNumeroPedido.removeAllItems();
            for (int ind = 0; ind < listaPed.size(); ind++)
            {
                Object o = listaPed.get(ind);
                Pedido p = (Pedido) o;
                jCmbNumeroPedido.addItem(p.getID());
            }
            if(listaPed.isEmpty())
                jCmbNumeroPedido.addItem("Nenhum Pedido.");
        } catch (Exception e)
        {
            Diversos.mostrarDados("Problemas ao carregar, inexistência de pedidos"
                    + e.getMessage(), "19:39", false);
            e.printStackTrace();
        }
    }
    public void mudaTema(int tema)//Troca o tema do frame
    {
        Color corFundo, corLetra, corLetraObj, corBotao, corCombo;
        if(tema == 0)
        {
            corFundo = new Color(151, 151, 151);
            corLetra = new Color(204, 204, 204);
            corLetraObj = Color.WHITE;/*new Color(51, 51, 51);*/
            corBotao = new Color(102, 102, 102);
            corCombo = corLetra;
        }
        else
        {
            corFundo = new Color(22, 73, 154);
            corLetra = Color.WHITE;/*(new Color(255, 255, 255);*/
            corLetraObj = Color.WHITE;/*new Color(102, 102, 255);*/
            corBotao = new Color(102, 102, 255);
            corCombo = corBotao;
        }
        jPanel1.setBackground(corFundo);
        jBtnConfirmacao.setBackground(corBotao);
        jBtnConfirmacao.setForeground(corLetra);
        jCmbNumeroPedido.setBackground(corCombo);
        jCmbNumeroPedido.setForeground(corLetraObj);
        
        JLabel labels[] = {jLabel2, jLblEntregador, jLabel14, jLabel3, jLabel2, jLabel4, jLabel6,
                          jLabel8, jLabel10, jLabel12};
        JLabel labelsObj[] = {jLblCliente, jLblMunicipio, jLblBairro, jLblRua, jLblNumero};
        for(int i = 0; i < labels.length; i++)
        {
            labels[i].setForeground(corLetra);
        }
        for(int i = 0; i < labelsObj.length; i++)
        {
            labelsObj[i].setForeground(corLetraObj);
        }
        
    }
    public void carregarPedido(Pedido p)
    {
        jLblEntregador.setText("-"+p.getEntregador().getNome());
        jLblCliente.setText(p.getNome());
        jLblMunicipio.setText(p.getEndereco().getMunicipio());
        jLblBairro.setText(p.getEndereco().getBairro());
        jLblRua.setText(p.getEndereco().getRua());
        jLblNumero.setText(String.valueOf(p.getEndereco().getNumero()));
    }
    public void limpar()
    {
        jLblEntregador.setText("-");
        jLblCliente.setText("");
        jLblMunicipio.setText("");
        jLblBairro.setText("");
        jLblRua.setText("");
        jLblNumero.setText("");        
    }
    private void jMnISairActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMnISairActionPerformed
    {//GEN-HEADEREND:event_jMnISairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jMnISairActionPerformed

    private void jMnISelecionarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMnISelecionarActionPerformed
    {//GEN-HEADEREND:event_jMnISelecionarActionPerformed
        // TODO add your handling code here:
        //Lembrar de adicionar mais catchs e testes. E criar um jDialog que retorne e só aceite numeros
        if(Diversos.leDados("Senha de ADM:\n**42**", "Who are you").equals("42"))
        {
            try
            {
                int entregador = Integer.parseInt(Diversos.leDados("Selecione o entregador:"
                + "\n"+Diversos.listarArray(entNome), "Entregador"));
                if(Diversos.intervalo(entregador, 0, listaEnt.size(), "Intervalo"))
                {
                    limpar();
                    Entregador ola = (Entregador)listaEnt.get(entregador - 1);
                    carregarCombo(ola.getID());
                    entregadorAtual = ola.getID();
                }
            }catch(Exception e)
            {
               Diversos.mostrarDados("Somente números", "...", false);
            }
        }
        else
        {
            Diversos.mostrarDados("Senha inválida", "...", false);
        }
    }//GEN-LAST:event_jMnISelecionarActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        // TODO add your handling code here:
        //Carrega a lista de entregadores
        try
        {
            listaEnt = dE.carrega();
            if(!listaEnt.isEmpty())
            {
                Entregador aa = (Entregador)listaEnt.get(0);//...
                entregadorAtual = aa.getID();
                carregarCombo(aa.getID());
            }
            entNome = new String[listaEnt.size()];
            for(int i = 0; i < listaEnt.size(); i++)
            {
                Entregador e = (Entregador)listaEnt.get(i);
                entNome[i] = e.getNome();
            }
        }catch(Exception e)
        {
            e.printStackTrace();
        }
    }//GEN-LAST:event_formWindowOpened

    private void jCmbNumeroPedidoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCmbNumeroPedidoActionPerformed
    {//GEN-HEADEREND:event_jCmbNumeroPedidoActionPerformed
        // TODO add your handling code here:
        //Troca o os dados do pedido de acordo com o ComboBox
        int posi = jCmbNumeroPedido.getSelectedIndex();
        if(posi == -1)
            posi = 0;
        if(!listaPed.isEmpty())
            carregarPedido((Pedido)listaPed.get(posi));
    }//GEN-LAST:event_jCmbNumeroPedidoActionPerformed

    private void jBtnConfirmacaoActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jBtnConfirmacaoActionPerformed
    {//GEN-HEADEREND:event_jBtnConfirmacaoActionPerformed
        // TODO add your handling code here:
        
        //Chama a tela de confirmação de venda
        int posi = jCmbNumeroPedido.getSelectedIndex();
        if(posi == -1)
            posi = 0;
        if(!listaPed.isEmpty())
            new JDialogConfirmacaoVenda(this, true, (Pedido)listaPed.get(posi)).setVisible(true);
    }//GEN-LAST:event_jBtnConfirmacaoActionPerformed

    private void jChkMnIBlueMintActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jChkMnIBlueMintActionPerformed
    {//GEN-HEADEREND:event_jChkMnIBlueMintActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jChkMnIBlueMintActionPerformed

    private void jChkMnILightGrayPropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jChkMnILightGrayPropertyChange
    {//GEN-HEADEREND:event_jChkMnILightGrayPropertyChange
        // TODO add your handling code here:
        System.out.println("jjjj");
    }//GEN-LAST:event_jChkMnILightGrayPropertyChange

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Metal".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(JFrmEntregadorPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(JFrmEntregadorPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(JFrmEntregadorPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(JFrmEntregadorPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new JFrmEntregadorPedido().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup btgTema;
    private javax.swing.JButton jBtnConfirmacao;
    private javax.swing.JCheckBoxMenuItem jChkMnIBlueMint;
    private javax.swing.JCheckBoxMenuItem jChkMnILightGray;
    private javax.swing.JComboBox jCmbNumeroPedido;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLblBairro;
    private javax.swing.JLabel jLblCliente;
    private javax.swing.JLabel jLblEntregador;
    private javax.swing.JLabel jLblMunicipio;
    private javax.swing.JLabel jLblNumero;
    private javax.swing.JLabel jLblRua;
    private javax.swing.JMenuBar jMBEntrega;
    private javax.swing.JMenu jMnEntregador;
    private javax.swing.JMenuItem jMnISair;
    private javax.swing.JMenuItem jMnISelecionar;
    private javax.swing.JMenu jMnSair;
    private javax.swing.JMenu jMnTema;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    // End of variables declaration//GEN-END:variables
}
